danskernesdigitalebibliotek/dpl-platform

- .github/workflows/dplsh-build-release.yaml
- tools/dplsh/Dockerfile
Updates the github action workflow that builds, tests and releases dplsh.
This update
- Reformats the file
- Fixes a bug where we triggered on the nonexistent "master" branch (should be main)
- Simplified the workflow by using a docker meta action for generating labels and tags
- Switched to buildx to do multiarch builds
The action tests itself, I've temporarily allowed it to always push so the runs made by this PR shuold create a full reelase.
> Update dpl build workflow and switch to multiarch

- .github/PULL_REQUEST_TEMPLATE.md
- .markdownlint-cli2.yaml
- documentation/runbooks/upgrading-lagoon.md
- infrastructure/.dplsh.profile
- infrastructure/README.md
- infrastructure/Taskfile.yml
- infrastructure/environments/dplplat01/lagoon/lagoon-remote-values.template.yaml
- infrastructure/environments/dplplat01/lagoon/lagoon-versions.env
- tools/dplsh/README.md
We have now upgraded the `dplplat01` env to the latest release of Lagoon ([v2.9.2](https://github.com/uselagoon/lagoon/releases/tag/v2.9.2)).
This bumps the env variables that we keep in the repo to align with that version.
Furthermore, we add the `overrideBuildDeployImage` chart variable to or env vars in order to pin the Build & Deploy image to the current Lagoon Remote version. Lagoon will default to `:latest` otherwise. This was introduced in [Lagoon Core chart version 1.2.0](https://github.com/uselagoon/lagoon-charts/releases/tag/lagoon-core-1.2.0).
This also adds documentation for the upgrade procedure.
Log in to https://ui.lagoon.dplplat01.dpl.reload.dk/projects/dpl-cms to confirm the current version.
https://reload.atlassian.net/browse/DDFDPDEL-206
> Upgrade Lagoon to latest version - DDFDPDEL-206

- documentation/runbooks/upgrading-lagoon.md
- infrastructure/Taskfile.yml
- infrastructure/environments/dplplat01/lagoon/lagoon-remote-values.template.yaml
- infrastructure/environments/dplplat01/lagoon/lagoon-versions.env
This fixes a bug with how the `overrideBuildDeployImage` chart var was defined, causing the build-deploy image to break during deploys.
> Fix build-deploy image in Lagoon

- infrastructure/Taskfile.yml
Since we are using `terraform -chdir=` to invoke terraform from an env subdir, we do not also need to ask Task to chdir for us first.
This fixes that behaviour.
> Fix cluster:auth task

- infrastructure/Taskfile.yml
This will bump the environment limit for all new projects when we create them, from 5 to 25.
This is probably a more sane default than the current upstream one.
> Bump limit for dev environments

- .gitignore
- documentation/runbooks/upgrading-aks.md
- infrastructure/environments/dplplat01/configuration/harbor/harbor-values.template.yaml
- infrastructure/environments/dplplat01/infrastructure/main.tf
- infrastructure/environments/dplplat01/lagoon/lagoon-versions.env
- infrastructure/terraform/modules/dpl-platform-environment/aks.tf
- infrastructure/terraform/modules/dpl-platform-environment/outputs.tf
- infrastructure/terraform/modules/dpl-platform-environment/providers.tf
- infrastructure/terraform/modules/dpl-platform-environment/variables.tf
I've upgraded the cluster to kubernetes veersion 1.24.6 and lagoon to 2.11.0
The upgrade revealed that we had a need for a more nuanced handling of versions of our node-pools so I updated the Terraform setup to allow us to control the versions of the individual nodepools.
I also noticed we where using a silly volume size for harbors pvcs and updated those.
This PR is made after the fact, so the review is mostly about reading through the updated documentation and the changes to Terraform.
DDFDRIFT-1
DDFDRIFT-14
> Upgrade Lagoon and AKS

- documentation/platform-environments.md
- documentation/runbooks/connecting-the-lagoon-cli.md
- infrastructure/Taskfile.yml
Add information about the current dplplat01 Lagoon instance needed to access the instance using the Lagoon CLI.
This can be helpful for developers working with DPL CMS without direct access to Kubernetes to access Lagoon as an alternative to using the Lagoon UI.
The PR also adds information about how DPL Platform developers can obtain this information for future instance so we remember it.
The PR also adds a potential tweak(?) to the current Terraform process found during the process.
1. Install the Lagoon CLI locally i.e. without using `dplsh`
2. Configure the CLI to access the current dplplat01 instance with the information in this PR
3. See that access works by running `lagoon whoami`
> Add Lagoon instance data

- documentation/runbooks/scale-aks.md
Adds a quick runbook for scaling the max/min nodepool size.
We should continue the work on this runbook as we run in to other scaling tasks.
Read through the runbook and see if it makes sense.
> Add a runbook for scaling aks

- documentation/runbooks/upgrading-support-workloads.md
- infrastructure/Taskfile.yml
- infrastructure/environments/dplplat01/configuration/versions.env
- tools/dplsh/Dockerfile
- tools/dplsh/README.md
- tools/dplsh/dplsh.sh
I'm working on streamlining our update procedure, and this is one of many steps towards that goal.
I've updated cert-manager and grafana, and documented the process. During my work I also implemented
a simple update-feature in dplsh, made is possible to run terraform init, and added a tool to dplsh
that allows us to verify cert-manager.
Mostly review of the docs, but you can also
- Check out the branch and verify that running `dplsh.sh --update` pulles the latest version of the image
- See that `task support:verify:cert-manager` works inside a shell
Mostly, just read through it and consider if it is in a state where you would be ok with taking the reigns.
> Update grafana, cert-manager. Improve docs and tools

- docs/runbooks/rabbitmq-broker.md
- docs/runbooks/upgrading-aks.md
- docs/runbooks/upgrading-lagoon.md
- infrastructure/Taskfile.yml
- infrastructure/environments/dplplat01/infrastructure/main.tf
- infrastructure/environments/dplplat01/lagoon/lagoon-versions.env
- infrastructure/terraform/modules/dpl-platform-environment/aks.tf
- infrastructure/terraform/modules/dpl-platform-environment/db.tf
- infrastructure/terraform/modules/dpl-platform-environment/dnsimple.tf
- infrastructure/terraform/modules/dpl-platform-environment/outputs.tf
- infrastructure/terraform/modules/dpl-platform-environment/providers.tf
- infrastructure/terraform/modules/dpl-platform-environment/variables.tf
- tools/dplsh/Dockerfile
This PR has various upgrades and fixes:
- Upgrade some tooling in `dplsh` image.
- Upgrade Lagoon to 2.16.0.
- Upgrade Terraform resources to conform with latest provider specs.
- Upgrade AKS cluster to Kubernetes 1.25.x and update documentation.
- Add runbook for RabbitMQ issue.
Everything here is already live, and the remote Terraform state is synchronized with these changes.
Go by commit.
> Lagoon + AKS upgrades

- infrastructure/dpladm/bin/dpladm-shared.source
The old  [lagoon images ](https://github.com/uselagoon/lagoon-images/tree/main)version breaks with the php 8.1 images
The lagoon images version tag we use in dpl-cms is just latest:
https://github.com/danskernesdigitalebibliotek/dpl-cms/blob/develop/lagoon/cli.dockerfile#L1
> Update lagoon images. The previous version is 2 years old.

- infrastructure/environments/dplplat01/configuration/ingress-nginx/ingres-nginx-values.template.yaml
- infrastructure/environments/dplplat01/configuration/versions.env
- Bump client_max_body_size in our Ingress controller config.
- Upgrade ingress-nginx to latest release.
This is already deployed to `dplplat01` and has been tested.
DDFDRIFT-32
> Bump client_max_body_size - DDFDRIFT-32

- tools/dplsh/Dockerfile
The guide in [the guide for provisioning Github repos step 2](https://danskernesdigitalebibliotek.github.io/dpl-docs/DPL-Platform/runbooks/add-library-site-to-platform/#step-2-provision-a-github-repository) suggests running `ssh-agent` and `ssh-add` inside dplsh, but these do not work as openssh is missing from the shell.
To make it easier to run everything inside the shell, we add the missing dependency, so the guide is now correct.
Build dplsh locally (`docker build . -t dplsh:local` in the /tools/dplsh folder, run the dplsh (`DPLSH_IMAGE=dplsh:local ../tools/dplsh/dplsh.sh` in the /infrastructure folder) and verify that `ssh-agent` and `ssh-add` execute without errors in the shell.
N/A
N/A
> Install openssh in dplsh to ensure we can run ssh-related commands inside it

- infrastructure/dpladm/env-repo-template/standard/.lagoon.yml
DDF wants two daily backups to be made; one around lunch and another in the evening. 
This PR changes the backup scheduling from running in the late evening to running at 12:00 and again at 19:00.
I don't see any good path to test this outside of the production envs. We should however have a look at the backup being made the day this PR is merged in. 
Ensure that the times entered at the hours place is 12 and 19.
https://reload.atlassian.net/browse/DDFDRIFT-35
> Back up at midday and again in the evening

- docs/runbooks/add-generic-site-to-platform.md
- docs/runbooks/add-library-site-to-platform.md
- docs/runbooks/deploy-a-release.md
- infrastructure/Taskfile.yml
- infrastructure/dpladm/bin/dpladm-shared.source
- infrastructure/dpladm/bin/sync-site.sh
- infrastructure/environments/dplplat01/sites.yaml
- infrastructure/terraform/modules/dpl-platform-env-repos/env_repositories.tf
Branch based on `add-canary-project` to get the Terraform changes from there included.
Adds staging envs for the plan where libraries might upload custom drupal modules. We specify this with the flag "plan: webmaster" in sites.yml.
Added a site `canary-customizable` which shows what is created by following this provisioning approach. See it in [lagoon](https://ui.lagoon.dplplat01.dpl.reload.dk/projects/customizable-canary) and on [Github](https://github.com/danishpubliclibraries/env-customizable-canary)
Read guides and verify that they make sense after the changes made.
Let me know if there are other places guides could be updated --- I don't know the full scope of them, or what the documentation approach is, yet, so if we need to document the `plan: webmaster` approach better, this is a …
> Staging envs for webmaster plan

- docs/infrastructure/README.md
Add read:packages to required scopes for Lagoon GitHub Tokens.
Without this [practice has shown that Lagoon will not be able to pull Docker images from GitHub](https://reload.zulipchat.com/#narrow/stream/355725-DDF-Drift/topic/Canary.20site.20kan.20ikke.20pull'e.20ghcr.2Eio.2Fdanskernesdigitalebiblio/near/428111029).
I think that practice has shown that it works.
> Add read:packages to required scopes for Lagoon GitHub Tokens

- docs/architecture/alertmanager-setup.md
- docs/runbooks/add-generic-site-to-platform.md
- docs/runbooks/add-library-site-to-platform.md
- docs/runbooks/remove-site-from-platform.md
- infrastructure/terraform/modules/dpl-platform-env-repos/lagoon_integration.tf
Draft because this is WIP as we run through runbooks and try to use them.
- Lagoon ssh keys as a prerequisite now also list where to create those keys
- When creating a site, a git-url must be provided - it is now clarified that the repo it points to does not need to exist before running the tasks in the runbook.
Read and verify the changes improve clarity, while staying as concise as possible.
N/A
> Guide adjustments

- infrastructure/Taskfile.yml
This sets all the keys significant to us to the values provided. Useful if a project is accidentally created with wrong settings.
Run on existing (but non-critical) project to see that given the two required values in [the guide for creating sites](https://danskernesdigitalebibliotek.github.io/dpl-docs/DPL-Platform/runbooks/add-library-site-to-platform/#create-a-lagoon-project-and-connect-the-github-repository) the project ends up in a correct state.
N/A
> Add task for updating lagoon project

- infrastructure/environments/dplplat01/lagoon/lagoon-remote-values.template.yaml
Enabling `sshCore` creates a service account which can be used by the lagoon-core-ssh service to provide ssh access to the projects. This, in turn, is required for running lagoon-sync, which executes inside the projects.
The changes have already been applied in the cluster. Here is the diff produced from applying the helm chart:
```diff
lagoon, lagoon-remote-ssh-core, ClusterRole (rbac.authorization.k8s.io) has been added:
- 
+ # Source: lagoon-remote/templates/ssh-core.clusterrole.yaml
+ apiVersion: rbac.authorization.k8s.io/v1
+ kind: ClusterRole
+ metadata:
+   name: lagoon-remote-ssh-core
+   labels:
+     helm.sh/chart: lagoon-remote-0.87.0
+     app.kubernetes.io/name: lagoon-remote
+     app.kubernetes.io/component: lagoon-remote-ssh-core
+     app.kubernetes.io/instance: …
```
> Enable sshCore in lagoon-remote chart

- infrastructure/environments/dplplat01/sites.yaml
Adds a site for teaching how to use the CMS. Like a pilot site, but not running a particular library.
The adding and deploying runbooks have been run. Verify that the site is running correctly.
[DDFDRIFT-57](https://reload.atlassian.net/browse/DDFDRIFT-57?atlOrigin=eyJpIjoiNGZkMjdlMTVmMzM3NGM0NDg4MGFmOGU4OTAwN2FmZGQiLCJwIjoiaiJ9)
[DDFDRIFT-57]: https://reload.atlassian.net/browse/DDFDRIFT-57?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add CMS school site

- infrastructure/environments/dplplat01/sites.yaml
Releases 2024.15.0 on canary. Has already been executed with `task site:sync SITE=canary`
Verify canary site looks to be running correct version.
[DDFDRIFT-53](https://reload.atlassian.net/browse/DDFDRIFT-53?atlOrigin=eyJpIjoiYWE3NDEwNTY2NWM1NGI3MGE4YzgyNmJmMmY4MTA4M2EiLCJwIjoiaiJ9)
[DDFDRIFT-53]: https://reload.atlassian.net/browse/DDFDRIFT-53?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Deploy 2024.15.0 on canary

- infrastructure/Taskfile.yml
- infrastructure/environments/dplplat01/sites.yaml
Releases [dpl-cms@2024.17.0](https://github.com/danskernesdigitalebibliotek/dpl-cms/releases/tag/2024.17.0) to all sites.
This has been tested on the canary site since yesterday.
Will be executed at 14:00
[DDFDRIFT-84](https://reload.atlassian.net/browse/DDFDRIFT-84?atlOrigin=eyJpIjoiNDBiZjllZTJjMDk2NDgyYWE0ZTIyMzJiNTVhZWZmNzYiLCJwIjoiaiJ9)
[DDFDRIFT-84]: https://reload.atlassian.net/browse/DDFDRIFT-84?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Release dpl-cms 2024.17.0 to all sites

- infrastructure/Taskfile.yml
- infrastructure/environments/dplplat01/configuration/cert-manager/.gitignore
- infrastructure/environments/dplplat01/configuration/cert-manager/cert-manager-values.yaml
- infrastructure/environments/dplplat01/configuration/cert-manager/zerossl-eabsecret.template.yaml
- infrastructure/environments/dplplat01/configuration/cert-manager/zerossl-issuer-production.template.yaml
- infrastructure/environments/dplplat01/sites.yaml
- infrastructure/task/scripts/provision-cert-manager.sh
Sets up a zerossl-based ACME cert issuer and starts using it has the primary issuer.
This lets us issue more certs, which we need because we've hit the LetsEncrypt rate limit.
This extends provision-cert-manager.sh to make it do all the things required for zerossl's issuer to work.
Read the code, does it seem reasonable?
Run `DIFF=1 task provision:cert-manager` and validate that the output (also pasted below for convenience) makes sense:
```diff
dplsh:~/host_mount$ DIFF=1 task support:provision:cert-manager
task: Task "_infra:terraform:init" is up to date
task: Task "cluster:auth" is up to date
task: [support:provision:cert-manager] task/scripts/provision-cert-manager.sh
> Diffing release
cert-manager, cert-manager, Deployment (apps) has changed:
apiVersion: apps/v1
kind: Deployment …
```
> Zerossl cert issuer

- infrastructure/environments/dplplat01/sites.yaml
Releases 2024.18.0 to canary. It has [already been run](https://github.com/danishpubliclibraries/env-canary/commit/1a642e552b5ed8f9762ccf35568b7d90f1474115)
[DDFDRIFT-75](https://reload.atlassian.net/browse/DDFDRIFT-75?atlOrigin=eyJpIjoiNDc3YzE0NGRlZmVhNGZjZDg4MTI5ODdmNDI1Yzk5MmUiLCJwIjoiaiJ9)
[DDFDRIFT-75]: https://reload.atlassian.net/browse/DDFDRIFT-75?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Deploy 2024.18.0 to canary

- infrastructure/environments/dplplat01/configuration/cert-manager/cert-manager-values.yaml
- infrastructure/environments/dplplat01/configuration/cert-manager/zerossl-eabsecret.template.yaml
Fixes zerossl secret name and namespace so we create it correctly
[DDFDRIFT-75](https://reload.atlassian.net/browse/DDFDRIFT-75?atlOrigin=eyJpIjoiNTQ5YTgyYjk2Nzg5NDQ1Yjg2MTU2NjVjOWQzNzEyYzYiLCJwIjoiaiJ9)
[DDFDRIFT-75]: https://reload.atlassian.net/browse/DDFDRIFT-75?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix zerossl-eabsecret name and location

- infrastructure/environments/dplplat01/lagoon/lagoon-remote-values.template.yaml
Executing many concurrent builds and hence image pushes to the in-cluster Harbor registry has shown to overload Harbor and possibly the [`docker-host` service](https://github.com/uselagoon/lagoon-service-images/tree/main/docker-host) in Lagoon.
Here we enable [a "QoS" feature in the lagoon-remote controller](https://github.com/uselagoon/remote-controller/blob/main/controllers/v1beta1/build_qoshandler.go#L22) which intentionally staggers the number of concurrent builds. 
We set the limit here to 15.
> Enable build QoS for Lagoon

- infrastructure/environments/dplplat01/configuration/ingress-nginx/ingres-nginx-values.template.yaml
We scaled to max 10 ingresses and the autoscaler immediately went to the limit. We will see if they stay there after the 5 minute stabilization window. If they do, or even if they stay close to (say 8+) it may be worth scaling the resources instead.
This commit suggests how to do that, while also increasing the autoscaling range to a more realistic one for our load.
Does this policy look reasonable?
The default resources section for ingresses looks like this:
```yaml
requests:
cpu: 100m
memory: 90Mi
```
So we are doing a significant increase
[DDFDRAFT-96](https://reload.atlassian.net/browse/DDFDRIFT-96?atlOrigin=eyJpIjoiMjExM2Q3YjMxMGNkNDBhNmE2MDI5ZWVhNGZkNzdmYzciLCJwIjoiaiJ9)
> Scale up ingresses more! perhaps

- infrastructure/Taskfile.yml
Cleans up task things:
- adds sites:check which shows a report on which sites from sites.yaml are responding correctly on /
- adds a task for terraform importing a github repo by site name (which also serves to document how we import resources in modules so we dont forget again - it is complex!)
- removes step that prints deploykey when syncing sites - we capture it, but no longer need it as output.
Run sites:check and see that it makes sense.
[DDFDRAFT-75](https://reload.atlassian.net/browse/DDFDRIFT-75?atlOrigin=eyJpIjoiMzQ1MDU2OTE2YzUwNGNlNjkwZWI2NTUyMTZiYTQxNmQiLCJwIjoiaiJ9)
> Various task stuff

- infrastructure/environments/dplplat01/sites.yaml
Upgrade Canary to 2024.18.2
Note that this update has not been deployed to the environment yet.
> Upgrade Canary to 2024.18.2

- infrastructure/environments/dplplat01/sites.yaml
Releases version 2024.18.2 to a select subset of libraries that are early movers
[DDFDRAFT-95](https://reload.atlassian.net/browse/DDFDRIFT-95?atlOrigin=eyJpIjoiZjI4MjNlNjM1YzI4NDM4ZGE5MWQ5NWY4YzI3NDA2NWEiLCJwIjoiaiJ9)
> Release 2024.18.2 to early movers

- infrastructure/Taskfile.yml
- infrastructure/dpladm/autoscaler.template.yaml
- infrastructure/dpladm/bin/dpladm-shared.source
- infrastructure/dpladm/bin/set-up-horizontal-autoscaler.sh
- infrastructure/dpladm/bin/sync-site.sh
The autoscaler handles scaling the nginx pod (which runs php and nginx) for a particular site.
This means that we will automatically scale to more instances if the system reaches higher load. Makes it less likely for us to encounter downtime when we go live with sites.
The current utilizations are set based on the (for now hard-coded from lagoon's side) resource requests for the pod. As the pod only requests 110 Mi memory, we set the bar for scaling up very high (500% of request -> 550 Mi). We are in talks with Amazee about enabling changes to the resource requests but it is not currently possible.
The autoscaler has been deployed on canary, herlev, billund and kobenhavn.
Run the script for a site, e.g. `customizable-canary`, and verify that a horizontalpodautoscaler is created in the …
> Add task for setting up an autoscaler for a site

- infrastructure/dpladm/bin/dpladm-shared.source
- infrastructure/dpladm/bin/sync-site.sh
- infrastructure/dpladm/env-repo-template/standard/.lagoon.yml
- infrastructure/environments/dplplat01/sites.yaml
This adds support for configuring cron schedule for an individual site for importing translations, and sets it for cms-school, so we get hourly translation imports in that one environment.
This allows us to define custom schedules for when translations should be imported.
Verify that the generated [.lagoon.yml](https://github.com/danishpubliclibraries/env-cms-school/blob/main/.lagoon.yml#L66-L71) looks correct
[DDFDRIFT-101](https://reload.atlassian.net/browse/DDFDRIFT-101?atlOrigin=eyJpIjoiZWZkMWY5ZDI2YjgzNDM0ZjhiZTdkZGE1Zjc1NjRhZjAiLCJwIjoiaiJ9)
[DDFDRIFT-101]: https://reload.atlassian.net/browse/DDFDRIFT-101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add support for `importTranslationsCron` in sites.yaml

- infrastructure/dpladm/bin/dpladm-shared.source
- infrastructure/environments/dplplat01/sites.yaml
Sets up known primary and secondary domains for the first three sites that will go live.
This means we are ready for them to point their DNS at us!
The changes has been executed in the infrastructure.
[DDFDRIFT-98](https://reload.atlassian.net/browse/DDFDRIFT-98)
[DDFDRIFT-98]: https://reload.atlassian.net/browse/DDFDRIFT-98?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add primary and secondary domains for billund,herlev,kobenhavn

- infrastructure/environments/dplplat01/configuration/ingress-nginx/ingres-nginx-values.template.yaml
Based on data from Grafana this seems like a reasonable level to request to be able to deal with spikes in traffic.
The ingresses (15!) are currently using around 300-400 Mi of memory and barely perceptible CPU. We would like to run on slightly fewer ingresses with room to scale up, so this request level (1.1Gi) should accomodate that wish.
Memory graph:
CPU graph:
We have 16 Gb memory available on each node, and allowing an ingress to be a memory heavy instance makes sense. Even at this level, we could accomodate 14 ingresses on a node, which is a lot! So it seems reasonable.
The change has been executed and is running in the platform.
[DDFDRIFT-96](https://reload.atlassian.net/browse/DDFDRIFT-96?atlOrigin=eyJpIjoiMjY1Yzk4MTBhMTQ2NGVmZGEwNGUwYmE4ZTQyYWI5ZTEiLCJwIjoiaiJ9)
[DDFDRIFT-96]: …
> Scale up ingress-nginx, based on metrics

- infrastructure/environments/dplplat01/configuration/prometheus/prometheus-values.yaml
Scales the disk size claimed by prometheus from 100 Gi to 500 Gi.
We have been hitting the full disk size with the metrics we are storing.
Has been executed (awaiting completion) in platform.
[DDFDRIFT-96](https://reload.atlassian.net/browse/DDFDRIFT-96?atlOrigin=eyJpIjoiN2FlOGI3NTYzMDEwNDlhZDk5YTJmODBmYjYwNzY4N2IiLCJwIjoiaiJ9)
[DDFDRIFT-96]: https://reload.atlassian.net/browse/DDFDRIFT-96?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Scale prometheus storage volume

- infrastructure/dpladm/autoscaler.template.yaml
The base levels for nginx-php pods (requests) 110 Mi memory and 0.02 cpu (by adding the requests for the two containers). Our estimates for a "large" site is that it will use 400 Mi memory and 0.1 cpu. At that point it may make sense to scale, so we adjust levels to fit that - still a very reasonable and low level.
So we set targets for the autoscaler that match a "large" instance and start scaling at that point. This means upping the CPU scaling to 500%, which is 0.1 cpu. Even this may be a low point to start scaling at...
Judge the reasoning. Should we up the targets even more to avoid needless scaling? We want to be able to pack into relatively few nodes here when load is low.
[DDFDRIFT-96](https://reload.atlassian.net/browse/DDFDRIFT-96)
[DDFDRIFT-96]: …
> Adjusted pod autoscaler for sites

- infrastructure/environments/dplplat01/sites.yaml
The early movers are now:
- cms-school
- herlev (go-live monday)
- billund (go-live monday)
The relevant site updates have been executed.
[DDFDRIFT-102](https://reload.atlassian.net/browse/DDFDRIFT-102?atlOrigin=eyJpIjoiZDhmZWVhMzA4ZWVkNDA5ZjhiMjdlODk3NzQyMWZhZDYiLCJwIjoiaiJ9)
[DDFDRIFT-102]: https://reload.atlassian.net/browse/DDFDRIFT-102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Release 2024.18.3 to early movers, recategorize who is an early mover

- infrastructure/environments/dplplat01/sites.yaml
After https://github.com/danskernesdigitalebibliotek/dpl-platform/pull/308 this ensures that we still have those domains live, in case anyone links to them, they will just redirect to the primary domain now instead
[DDFDRIFT-97](https://reload.atlassian.net/browse/DDFDRIFT-97)
[DDFDRIFT-97]: https://reload.atlassian.net/browse/DDFDRIFT-97?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add internal domains as secondary domains for sites with primary domains

- infrastructure/environments/dplplat01/sites.yaml
This PR updates the early movers to use CMS versino 2024.19.0 and the all other sites to use 2024.18.3
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-110
> Update site yaml for realeasing 2024.19.0

- infrastructure/environments/dplplat01/infrastructure/main.tf
- tools/dplsh/Dockerfile
This upgrades AKS and kubectl to the latest supported 1.27 release.
> Upgrade AKS and kubectl versions to latest supported 1.27.x.

- infrastructure/environments/dplplat01/sites.yaml
Sets primary and secondary domains for Aalborg Bibliotekerne.
This has been executed in the infrastructure.
[DDFDRIFT-117](https://reload.atlassian.net/browse/DDFDRIFT-117)
[DDFDRIFT-117]: https://reload.atlassian.net/browse/DDFDRIFT-117?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Aalborg go live

- infrastructure/environments/dplplat01/infrastructure/main.tf
- infrastructure/terraform/modules/dpl-platform-environment/aks.tf
- infrastructure/terraform/modules/dpl-platform-environment/variables.tf
- ✅ Changes the format for defining node pools to allow dynamically defining more.
- ✅ Creates new app and admin node pools on Standard_B8ms (bigger node machines!)
- ✅ Scales down existing node pools to move load to new node pools
- ✅ Removes old node pools
This branch is up to date with Terraform state and *main is not anymore!*
[DDFDRIFT-108](https://reload.atlassian.net/browse/DDFDRIFT-108?atlOrigin=eyJpIjoiY2I5ODVkZWNmMGU0NDMwOGJmNDM1ZTNmNDM4OGVlMGQiLCJwIjoiaiJ9)
[DDFDRIFT-108]: https://reload.atlassian.net/browse/DDFDRIFT-108?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> New node pools

- infrastructure/Taskfile.yml
- tools/dplsh/Dockerfile
Given primary- and secondary-domains in sites.yaml this task checks through all domains to see if any have a CAA record attached. If they do, this is reported.
CAA records present in a DNS record means that we *must* specify the certificate authority allowed to provision certificates for the domain. If any of the libraries have this record we must get them to adjust it prior to going live.
Build and deploy dplsh locally and check that `task sites:check-caa` runs correctly.
[DDFDRIFT-94](https://reload.atlassian.net/browse/DDFDRIFT-94)
[DDFDRIFT-94]: https://reload.atlassian.net/browse/DDFDRIFT-94?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Task for checking for CAA records in all sites in sites.yaml

- infrastructure/Taskfile.yml
We use this to get an indication of how many sites have started using the system.
It has the nice added benefit of putting the frontpage in varnish's cache.
[DDFDRAFT-113](https://reload.atlassian.net/browse/DDFDRIFT-113)
> Add task for looping through sites and checking if they have a logo set up

- infrastructure/environments/dplplat01/sites.yaml
This PR bumps the version for all sites to 2024.20.2
It has not yet been rolled out
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-119
> bump version for deafult and canary

- infrastructure/environments/dplplat01/sites.yaml
It patches 2024.20.2 and adds that as a repeatable image source we can roll out to specific sites. It also allows us to keep track of state without polluting sites.yaml
> patch for 2024.20.2

- infrastructure/dpladm/bin/dpladm-shared.source
- infrastructure/dpladm/bin/sync-site.sh
- infrastructure/environments/dplplat01/sites.yaml
Default is autogenerting UNLESS primary domain is set. Now you can override with custom behavior with the custom flag.
The change has been executed in the platform for canary specifically.
Verify that the [change from applying this change](https://github.com/danishpubliclibraries/env-canary/commit/e69db0f910f4d28392a4bab9677a635d5348cfc6) looks reasonable.
[DDFDRIFT-120](https://reload.atlassian.net/browse/DDFDRIFT-120?atlOrigin=eyJpIjoiZmJhNTMzZDhmYzFlNDQ0NDllNDA3MzdlZDRiZWM0ZDkiLCJwIjoiaiJ9)
[DDFDRIFT-120]: https://reload.atlassian.net/browse/DDFDRIFT-120?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Support `autogenerateRoutes` flag on sites, which overrides default autogeneration behavior

- infrastructure/Taskfile.yml
- incomplete-deployments lists all sites whose latest deployments are not in status "complete", so we can track which ones failed during deployment
- grep-in-deploy-log takes a NEEDLE and returns for each site the number of matches in their latest deploymentss log
Run the two tasks and see if they work as expected.
[DDFDRIFT-123](https://reload.atlassian.net/browse/DDFDRIFT-123)
[DDFDRIFT-123]: https://reload.atlassian.net/browse/DDFDRIFT-123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add tasks `sites:{incomplete-deployments,grep-in-deploy-log}`

- infrastructure/environments/dplplat01/sites.yaml
This PR removes the Varnish and NGINX routes. This should fix a linking issue that Aalborg is having post-databreach
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-127
> Fix webserver links

- infrastructure/environments/dplplat01/infrastructure/main.tf
Migrates to node pools with slightly lower max_pods setting. This should give workloads more breathing room to use more resources when needed.
We are limited by Lagoon hardcoding resource requests for pods. At 100 pods it seemed to push the limits of the nodes quite harshly, resulting in slow scheduling and some lowered performance.
The change has been executed in the platform.
[DDFDRIFT-128](https://reload.atlassian.net/browse/DDFDRIFT-128)
[DDFDRIFT-128]: https://reload.atlassian.net/browse/DDFDRIFT-128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Node pools fewer max pods

- infrastructure/Taskfile.yml
- infrastructure/environments/dplplat01/contacts-and-their-sites.yaml
This PR adds some tasks, one for sending emails, one for generating passwords for the admin user on main environments and a higher level abstraction which couples the two former tasks together to sent emails to library contact persons. 
This should be read through. It can be easily tested by running either of the tasks. 
The format for the /contacts-and-their-sites.yaml can be seen inside it. Just change the sitename, name(s) and the email(s)
If the az cli complains. run these two commands one after the other: 
`az extension remove -n communication
az extension add -n communication -y
`
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-60
https://reload.atlassian.net/browse/DDFDRIFT-85
> Enable sending mails to contacts with the admin password and info about where to login

- infrastructure/Taskfile.yml
Add support for skipping steps in deployments so we can use our knowledge of a deployment situation to only take necessary steps + get faster deploys
Try different SKIP_* combinations when running sites:sync and verify they work.
[DDFDRIFT-95](https://reload.atlassian.net/browse/DDFDRIFT-95?atlOrigin=eyJpIjoiZGU5M2Q0OGE3OWFjNGEwMzhmYjVjOGRlNTcxODUxYzYiLCJwIjoiaiJ9)
[DDFDRIFT-95]: https://reload.atlassian.net/browse/DDFDRIFT-95?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Allow skip steps in sites:sync

- infrastructure/Taskfile.yml
- infrastructure/environments/dplplat01/sites.yaml
This PR releases 2024.22.1 to all sites. 
It also removes the old groups `next`and `patch` and replaces the sites that were assigned them, to the `deafult` group.
No
This should be read through. Please also open up the `sites.yaml` file and check that none of the old groups are assigned to any sites. 
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-134
> Release 2024.22.1

- infrastructure/Taskfile.yml
this add a one-time task that allows us quickly send a new admin their credentials
I have already thouroughly tested this. If you have the time to test it can be done by using canary and your own email in the following  command: 
`PROJECT="canary" USERNAME="someUserName" MAIL="your@mail.tld" CONTACTNAME="yourName" PASSWORD="1234Test" task site:local-admin:password:create-and-notify`
Sanity check it
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-37
> one time password and notify admins

- infrastructure/Taskfile.yml
This PR does 2 things:
1) It makes the `mail:sent` task easier for other tasks to make use of
2) It makes resetting an admins password way faster
This PR can be tested against the `canary` environment by running the `site:local-admin:password:reset` task and the `    site:local-admin:password:create-and-notify`task. I have tested it thoroughly though, so it's probably not necessary.  
Read it through and check that it makes sense
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-124
> Quicken admin password reset

- infrastructure/environments/dplplat01/sites.yaml
This PR does what it says on the tin
This should be carefully read through. Please go to the domains for each site, and verify that the primary is infact the primary domain and that the secondary domain redirects to the primary domain
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-136
> set domains and autoGenerateRoutes for Struer and Faxe

- infrastructure/Taskfile.yml
This PR makes it really easy to change `local_administrators` of an environment to `administrators` thereby enabling them to upload modules to their site
This should be tested by adding a `local_administrator` to canary og cms-school and the running the task and seeing that they switched roles to `administrator`
Read it through and test it
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-136
> Local admin to admin task

- infrastructure/environments/dplplat01/sites.yaml
This PR assigns København, Herning, Faxe, Tårnby, Århus and Aalborg to the webmaster plan. When run, this will result in them having `moduletest` environments. 
**This has only been run on canary and not the actual libraries** 
This should be read throuh, ensuring that the libraries mentioned above has the property `plan`set to `webmaster`
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-137
> Webmaster pilot sites

- infrastructure/dpladm/bin/dpladm-shared.source
- infrastructure/dpladm/bin/sync-site.sh
This PR fixes the moduletest environment by ensuring that the .lagoon.yaml file is valid. This is done by having it match the one on main. 
Read it through and make sure that it makes sense. 
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-137
> ensure that the .lagoon.yaml file on moduletest is valid

- infrastructure/environments/dplplat01/infrastructure/main.tf
This PR is related to the build and deploy errors we are encountering. The theory right now is that, because Lagoon has decided on `ressrouce_req` and set that to low, the workloads are requesting way more resources than available on the node. Therefore we can try to have more nodes for Kubernetes to spread the workload on. 
Just read it through and see that the `min` has been set to 9
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-148
> up the minimum number of nodes to 9

- infrastructure/dpladm/bin/dpladm-shared.source
- infrastructure/environments/dplplat01/sites.yaml
Allows a new value for `autogenerateRoutes` called `"redirect"` which indicates that we want traffic to the auto-generated routes (nginx.main.<site>... and varnish.main.<site>...) to be redirected to the primary domain set on the site.
Tested and executed on canary, c.f. https://nginx.main.canary.dplplat01.dpl.reload.dk/
Tested the equivalence with previous approach for aalborg, c.f. changes (only the order has changed): https://github.com/danishpubliclibraries/env-aalborg/commit/e883478b78216710c46c1f78b5bc5cae94c4d50a
The move of launched domains `autogenerateRoutes: {true->"redirect"}` has **not** been executed.
Read through and validate that this approach makes sense. Test the executed changes mentioned above.
[DDFDRIFT-138: Få domæner sat op for Struer og Faxe så de kan gå live når …
> Autogenerate redirect routes

- infrastructure/dpladm/bin/dpladm-shared.source
- infrastructure/dpladm/env-repo-template/standard/lagoon/conf/nginx/http_log_format.conf
- infrastructure/dpladm/env-repo-template/standard/lagoon/conf/nginx/metrics/version.json
- infrastructure/dpladm/env-repo-template/standard/lagoon/conf/nginx/metrics/version.txt
- infrastructure/dpladm/env-repo-template/standard/lagoon/conf/nginx/server_append_drupal_serve_metrics.conf
- infrastructure/dpladm/env-repo-template/standard/lagoon/nginx.dockerfile
- Adds /_metrics/version{.json,.txt,} endpoint to all sites which exposes information about the image running in this instance.
- Sets up JSON logging from the nginx instance consistent with the format we use for the ingress
These changes will be used for Grafana dashboards.
The changes have been executed on canary.
Review logs from canary using `kubectl logs` and check the metrics endpoint on https://bibliotest.deranged.dk/_metrics/version - does it make sense?
[DDFDRIFT-150](https://reload.atlassian.net/browse/DDFDRIFT-150)
[DDFDRIFT-151](https://reload.atlassian.net/browse/DDFDRIFT-151)
[DDFDRIFT-152](https://reload.atlassian.net/browse/DDFDRIFT-152)
[DDFDRIFT-150]: https://reload.atlassian.net/browse/DDFDRIFT-150?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l …
> Version metrics endpoint + JSON logs from nginx

- infrastructure/dpladm/env-repo-template/standard/.lagoon.yml
Ensures that deploy-time post-rollout tasks fail loudly. Currently they fail silently, and deployment continues, and we may miss them.
Based on https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/1113
I ran a diff between env-canary's .lagoon.yml and dpl-cms' version of the same time, and made these changes. The remaining changes seem intentional.
Executed on canary.
See the changes made to env-canary here: https://github.com/danishpubliclibraries/env-canary/compare/9fe6e48c65275b8bc737db7caff46d2860878836...f51ae445ee0e0d513016275c38e9095492749ef1
Do they seem reasonable?
[DDFDRIFT-111](https://reload.atlassian.net/browse/DDFDRIFT-111)
[DDFDRIFT-111]: https://reload.atlassian.net/browse/DDFDRIFT-111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNv …
> Fail-fast in post-rollout

- infrastructure/environments/dplplat01/sites.yaml
Deploy 2024.27.0 to canary.
This has already been applied using `task site:sync`.
> Deploy release 2024.27.1 to Canary

- infrastructure/Taskfile.yml
- infrastructure/environments/dplplat01/infrastructure/main.tf
- infrastructure/terraform/modules/dpl-platform-environment/aks.tf
- infrastructure/terraform/modules/dpl-platform-environment/variables.tf
Slowly switches to E-series boxes for our workloads. They are high in memory and lower in CPU, which fits our usage profile better for the money.
Also improved SLA for AKS cluster and database settings.
Now fully switched over. Has been executed.
> Switch to new nodepool

- infrastructure/Taskfile.yml
Currently we have no good way of identifying failing backups. Our best way to check that they are running for all sites is to check when the last succesfull backup was run.
To help in this process we add a new task which retrieves this from each site in Lagoon and prints it.
Use silent to avoid printing the shell command for each site. This makes the output more compact.
Try running the task for yourself.
> Add task to show the latest backup for each site

- infrastructure/dpladm/env-repo-template/standard/.lagoon.yml
This PR activates the cron-jobs, which should fix integrations that aren't working one moduletest at the moment due to missing tokens. 
I have rolled it out on Taarnby, se please check there if this fixes it. 
Read it through.
https://reload.atlassian.net/browse/DDFDRIFT-174
> add cron-jobs to moduletest

- infrastructure/environments/dplplat01/lagoon/lagoon-remote-values.template.yaml
Lowers concurrency when building sites in Lagoon.
Has been executed in infrastructure.
DDFDRIFT-96
> Lower max builds concurrent in lagoon to 5

- tools/dplsh/Dockerfile
The latest release is 0.21.3 - not 0.23.1.
With the current change the Lagoon CLI will no longer been installed.
Fix version of Lagoon CLI
The latest release is 0.21.3 - not 0.23.1.
With the current change the Lagoon CLI will no longer been installed.
> Fix version of Lagoon CLI

- infrastructure/environments/dplplat01/sites.yaml
Did it the other way around, by accident.
The canary site is already deploying :)
> Test release 2024.32.1 on canary

- infrastructure/Taskfile.yml
- infrastructure/dpladm/bin/sync-site.sh
- infrastructure/dpladm/env-repo-template/standard/.lagoon.yml
- infrastructure/dpladm/env-repo-template/standard/lagoon/cli.dockerfile
- infrastructure/environments/dplplat01/sites.yaml
- infrastructure/task/scripts/adjust-resource-requests.sh
This PR adjusts the memory requests for the pods: cli, nginx, varnish and redis. This should help kubernetes to better allocate workloads
This can be run without any concerns. Please do so. 
Test run it and read it through
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-96
> Set resource req  in all the desired pods in the wanted namespaces

- infrastructure/environments/dplplat01/configuration/ingress-nginx/ingres-nginx-values.template.yaml
`proxy_upstream_name` is part of the default logging, but when we changed to custom logging, it was left out. This adds it back in, into the custom logging.
Should not be necessary
Nope
None - for now.
> Add proxy_upstream_name to nginx logging

- infrastructure/environments/dplplat01/sites.yaml
it rolls the 35.1 release on to canary
just read it 
no
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-200
> roll out 35.1 on canary

- infrastructure/dpladm/bin/sync-site.sh
- infrastructure/environments/dplplat01/sites.yaml
This PR allows us to have seperate versions on WM and prod sites
Read it through and test it on canary 
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-154
> Seperate versions between moduletest and main

- infrastructure/.dplsh.profile
This gives the PS1 some color for easier recognition and adds kc as a working alias to kubectl
No
> improve the UX of the dplsh

- infrastructure/environments/dplplat01/sites.yaml
It releases 2024.35.1 to almost all libraries, but keeps Roskilde, Silkeborg and Albertslund on 33.
Read it throug. Especially the tag for the ones staying on 33
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-200
> up default and webmaster releases to 35.1 but let 3 libraries stay on 33

- infrastructure/dpladm/env-repo-template/standard/lagoon/conf/nginx/server_append_drupal_rewrite_legacy_search_works.conf
- infrastructure/dpladm/env-repo-template/standard/lagoon/nginx.dockerfile
This is a mirror of danskernesdigitalebibliotek/dpl-cms#1508 which applies the change for the NGINX image to the environment template.
If accepted then we must ensure that the changes to the template are propagated to the sites.
Consider checking the test in the danskernesdigitalebibliotek/dpl-cms#1508
https://reload.atlassian.net/browse/DDFFORM-978
> Redirect legacy paths for library search and materials to new paths

- infrastructure/environments/dplplat01/sites.yaml
Removes secondary domains from Køge Bibliotek, which they want to manage themselves.
No
No
None
> Remove secondary domains from Køge bibliotek

- infrastructure/environments/dplplat01/sites.yaml
set the moduletest environments version
Just read it
No
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-200
> set version for moduletest

- infrastructure/environments/dplplat01/sites.yaml
Deploy release 2024.36.0 to canary
It has already been applied.
> Deploy release 2024.36.0 to canary

- infrastructure/environments/dplplat01/sites.yaml
This releases 36 to all, but the webmasters libraries. It makes a few changes. The libraries we kept on 33 i now being moved the right releases. The moduletest-release is now part of the webmaster anchor instead. 
No
Please read it thoroughly
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-209
> Release 36

- infrastructure/dpladm/bin/dpladm-shared.source
Add some arguments checking to syncEnvRepo so it won't work with a missing tag, for instance.
Nope, I'm not entirely sure of the environment to run it in. But the `if` syntax has been checked with shellcheck.
> Check that arguments is defined in syncEnvRepo

- infrastructure/environments/dplplat01/sites.yaml
It adds a staging library site for DDF to test on. This allows us to go back to using canary for testing all sorts of things in a sandboxed yet production like environment
Just read it
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-189
> add a staging site

- infrastructure/environments/dplplat01/sites.yaml
Releases latest release 2024.37.0 to sites on redaktør plan and moduletest sites on webplatster plan.
> Release 2024.37.0 to moduletest sites for webmaster and main sites for others

- infrastructure/environments/dplplat01/configuration/ingress-nginx/ingres-nginx-values.template.yaml
- infrastructure/environments/dplplat01/lagoon/lagoon-remote-values.template.yaml
We isolate lagoon docker host to its own node pool, and we move the ingress controllers to the production nodes. We also adjust HPA settings for the ingress controllers.
No
No
DDFDRIFT-86
> Add tolerations and affinity to lagoon docker host and ingress-controller

- infrastructure/environments/dplplat01/sites.yaml
Deploy release 2024.38.1 on Canary. Release 2024.38.0 turns out to cause problems during deployments. Addressing this required another release.
> Deploy release 2024.38.1 on Canary

- infrastructure/task/scripts/cleanup-dev-envs.sh
Use force when deleting environments during cleanup
Otherwise the script will stop after deleting a single environment.
Using --force uses yes for interactive prompts and allows the script to continue across all environments.
Before:
```
➜  scripts git:(main) ./cleanup-dev-envs.sh
PR #1440 is CLOSED. Closing development environment: pr-1440.
✔ Yes
Result: success
➜  scripts git:(main) ./cleanup-dev-envs.sh
PR #1228 is CLOSED. Closing development environment: pr-1228.
✔ Yes
Result: success
➜  scripts git:(main) ./cleanup-dev-envs.sh
PR #1476 is CLOSED. Closing development environment: pr-1476.
✔ Yes
Result: success
```
After
```
➜  scripts git:(main) ✗ ./cleanup-dev-envs.sh
PR #1478 is CLOSED. Closing development environment: pr-1478.
Result: success
PR #1521 is CLOSED. Closing development …
```
> Use force when deleting environments during cleanup

- infrastructure/environments/dplplat01/sites.yaml
[Add an anchor for webmaster sites using the latest version on main](https://github.com/danskernesdigitalebibliotek/dpl-platform/commit/89bce9345c8fb3204bd5c4b35e0e6a6b4c6162c5)
Normally webmaster sites use a previous version on their main
(production) environment and the latest version on their moduletest
environment.
However some sites want to use the latest version on both
environments.
Create an anchor to use for these sites.
Reference the new anchor for CMS School and Silkeborg as requested by
the business.
Reference the new anchor on staging to ensure that this follows the
latest version. This makes sense to enable testing there.
Deploy the changes to the three sites in question.
One has to understand the intricacies of mulitple YAML references, overrides etc. to understand how the …
> Use latest version on some webmaster sites

- infrastructure/environments/dplplat01/sites.yaml
Bump release for editors and moduletests to 38.1
Dont test - just read
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-222
> release 38.1 to editors and moduletests

- infrastructure/environments/dplplat01/sites.yaml
[Update customizable canary for testing](https://github.com/danskernesdigitalebibliotek/dpl-platform/commit/b33546d3e8243233c32d0eebe6f8e836f2e3f305)
We need an environment which follows the webmaster release cycle and
can be used for testing.
Move the definition of customizable canary next to the current canary
environment and replace the current reference defining release numbers
with explicit release numbers.
Now we can deploy release 2024.35.2 to Customizable Canary.
> Release 2024.35.2 on Customizable Canary

- infrastructure/environments/dplplat01/sites.yaml
This releases 35.2 to webmaster production sites and 38.2 to editor production sites as well as webmaster webmoduletest sites.
This should be read through carefully
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-227
> release 35.2 and 38.2 to their respective libraries

- infrastructure/Taskfile.yml
It adds the ability to set the cluster into deploy mode and back into business mode
Please run the both tasks on after the other.
After having set the cluster in deploy mode, go here: https://portal.azure.com/#@reloadas.onmicrosoft.com/resource/subscriptions/8ac8a259-5bb3-4799-bd1e-455145b12550/resourceGroups/rg-env-dplplat01/providers/Microsoft.ContainerService/managedClusters/aks-dplplat01-01/nodePools
The app6 nodepool should now have 4 nodes and the system2 nodepool should have 5. 
Then set the cluster back into business mode and check that, the app6 pool has 2 nodes and the system2 pool has 3 nodes. 
Run the tasks and read it through
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-240
> Task for cluster deploy mode

- infrastructure/environments/dplplat01/sites.yaml
Set routes on the libraries going live in week 44: https://reload.zulipchat.com/#narrow/channel/435665-DDF---Drift.2B/topic/Udrulning.20i.20uge.2044
just read it
Just read it
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-244
> add routes to libraries going live in week 44

- infrastructure/environments/dplplat01/sites.yaml
It releases new versions to the libraries. 
The editors and weekly updated webmasters will go directly 44.0, as will the regular webmasters moduletest.
The webmasters on a regular schedule will have their production sites updated to last weeks update (43.1).
Herning will, as requested(https://reload.zulipchat.com/#narrow/channel/419623-DDF.2B/topic/Release.202024.2E44.2E0/near/479639216), stay on 39.1 for another week. Their moduletest however will be upated to 44.0.
Just read it 
read it 
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-247
> Release 44.0

- infrastructure/environments/dplplat01/lagoon/lagoon-remote-values.template.yaml
This sets the number of parallel builds down to 8. 
We go a lot of errors when building 15 at the same time. 
We also got some errors while building 10 at a time, so I want to try to find level at which we have as close to none as possible.
No - this has been run already
> only build 8 environments at a time

- infrastructure/Taskfile.yml
It finds all webmasters and resets all their moduletest environments by copying their files and databases from prod to moduletest and then running another deploy. 
Don't run the task unless it needs to. I have a tested it on the a list of canaries. 
Just read it
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-251
> Task to reset all moduletests

- infrastructure/Taskfile.yml
- infrastructure/task/scripts/redeploy-failed-deployments.sh
This is hopefully a little nifty task that will make it faster and easier for us to redeploy failed deployments for both main and moduletest environments. 
I have done this as most deployment problems are solved by runnning them again. 
We should still investigate why deployments fail.
Just run it
Read it and test it 
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-252
> Task to restart failed deployements that are not from the dpl-cms project

- infrastructure/dpladm/env-repo-template/standard/lagoon/conf/nginx/location_prepend_drupal_authorize.conf
- infrastructure/dpladm/env-repo-template/standard/lagoon/conf/nginx/location_prepend_drupal_update.conf
- infrastructure/dpladm/env-repo-template/standard/lagoon/nginx.dockerfile
Make `update.php` accessible. Webmaster libraries needs to use it to run module update hooks after uploading a new version of a custom module. Lagoon disables this per default.
[DDFHER-94](https://reload.atlassian.net/browse/DDFHER-94)
[DDFHER-94]: https://reload.atlassian.net/browse/DDFHER-94?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Ddfher 94 update php access

- infrastructure/environments/dplplat01/sites.yaml
This releases 47.1 onto: 
editors production,
Webmaster modultests
Canary sites moduletests
It also upgrades Hernings prod to 46.0
This should be read through
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-260
> Release 47.1

- tools/dplsh/dplsh.sh
If the file doesn't exist, Docker will create a root owned empty directory instead, which will mess any git command run on the host.
> Handle no ~/.gitconfig

- tools/dplsh/Dockerfile
This will upgrade some packages (Task, Stern and the Lagoon CLI) to latest releases, as `dplsh` was lagging behind somewhat. 
I've tested this against the main cluster with a locally built shell without issues.
> dplsh upgrades - nov 2024

- docs/runbooks/reset-moduletest.md
- docs/runbooks/ui-reset-moduletest.md
- infrastructure/Taskfile.yml
Adds `sites:webmaster:reset-moduletest` task and updates resetting moduletest runbooks.
We're getting requests to reset sigle sites, so a command that does exactly that is handy and eliminates the risk of fumbling the four required parameters to `site:environment:sync`.
Added note to resetting module rulebook that it's in fact not quite a proper reset.
Added the missing rulebook about using resetting moduletest sites using `dplsh` to aid discoverability.
> Moduletestsyncing

- infrastructure/Taskfile.yml
Bitter experience has shown that, contrary to documentation and what reading of the source may lead you to believe, that `--create-db` apparently does *not* drop and recreate the database, for unknown reasons. So explicitly run `drush sql-drop`.
> Explicitly drop database when syncing moduletest

- infrastructure/environments/dplplat01/sites.yaml
Update editor and moduletest sites to 2024.49.0.
Also remove the hackery needed in the last deployment to get 2024.48.1 out on webmaster-with-defaults sites.
> Update editors ond webmasters to 2024.49.0

- infrastructure/dpladm/env-repo-template/standard/docker-compose.yml
We have a theory that the reason the database is being hit hard in deployments is because when Kubernetes moves things around it implicitly clears the caches. So try with a persistent Redis cache.
> Use persistent Redis

- infrastructure/dpladm/env-repo-template/standard/docker-compose.yml
Lagoon warns that it is not possible to change the service type after it has been deployed. Consequently we need to roll this back for now.
Reverts danskernesdigitalebibliotek/dpl-platform#545
> Revert "Use persistent Redis"

- infrastructure/environments/dplplat01/sites.yaml
it adds a route to Bornholms library. They only have on `bibliotek.brk.dk`
It should just be read
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-271
> add route to bornholms library

- docs/runbooks/weekly-release-to-editors-and-moduletests.md
It remove steps that we do not want to use at this moment, as they move the pod around. It is not possible for us to move pod around without interupting the live sites, as no PodDisruptionBudget has been installed
> Remove unused step

- infrastructure/environments/dplplat01/sites.yaml
Releases:
Editors and weekly webmasters: 2024.50.0
Webmaster prod: 2024.49.0, except Albertslund, Faxe, Herning, Roskilde, Sydslesvig and Tårnby, which stay on 2024.47.2
Webmaster moduletest: 2024.50.0
> Release week 50

- .markdownlint-cli2.yaml
- docs/runbooks/troubleshoot-statuscake-monitor.md
Add an initial runbook for how to handle common errors resulting in StatusCake alerts
This is an initial attempt at creating a runbook for how to handle monitoring alerts in StatusCake.
Not really.
Read it through and consider whether it makes sense to you.
https://reload.atlassian.net/browse/DDFHER-184
> Add runbook for troubleshooting StatusCake monitor errors

- infrastructure/dpladm/env-repo-template/standard/docker-compose.yml
Increase size of NGINX persistent storage to 10Gi.
This is the size limit currently set by the largest library site. Make this the default for all sites.
We currently do not have a good way to set individual size limits per site. This has created a suboptimal workflow where the site in question has to be updated manually after each workflow for the deployment to complete.
We could introduce a way to control this per site in sites.yaml but it would not provide much value. We pay for storage used - not reserved. Consequently increasing the limit for all sites should not increase costs considerably until it is actually used.
All this in mind we increase the size of the the persistent storage for the Lagoon default of 5Gb to 10Gb.
https://docs.lagoon.sh/concepts-basics/docker-compose-yml/#pers …
> Increase size of NGINX persistent storage to 10Gi

- infrastructure/Taskfile.yml
Lagoon CLI had it's flags updated with version 0.30 (we are running 0.31) and these flags haven't been updated, when we updated to 0.31 here  https://github.com/danskernesdigitalebibliotek/dpl-platform/pull/523. 
Here's the docs describing the update: https://dev.to/uselagoon/upcoming-lagoon-cli-release-v0300-theres-a-lot-of-changes-13d8
This should be tested by firstly updating the dplsh image to the newest one. 
Then run `SITE=canary site:full-sync` It should now work. 
Read it and test it
[DDFBRA-328](https://reload.atlassian.net/browse/DDFBRA-328)
[DDFBRA-328]: https://reload.atlassian.net/browse/DDFBRA-328?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update flags to match 0.30's new flags

- tools/dplsh/dplsh.sh
Shows dplsh's version on start up. This will make it easier for us to know which version we are running and enable troubleshooting
Please do, simply restart the shell
> display dplsh version on start up

- infrastructure/Taskfile.yml
The new consumers for the BNF and the GO project need a secret and a password set in every project or else an exception will be thrown.
IMPORTANT: This is a temporary solution. Real passwords and secret should be set in the future.
https://reload.atlassian.net/browse/DDFBRA-328
This has been tested on the canary site, where you can now see the variables present:
> Ensure consumer passwords and secrets in projects

- docs/runbooks/how-release-a-new-version-for-approval-testing.md
We update both staging main and moduletest.
> Document the de facto staging deployment procedure

- infrastructure/Taskfile.yml
Tasks that contain a lot of shell code and echo their own status should be silenced to limit the amount of (useless) output.
> Turn off echo'ing for some tasks

- infrastructure/environments/dplplat01/sites.yaml
It removes holbaeks secondary domain which they are not using. 
It has been run. 
Just read it
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?search=go%20live%20holb&selectedIssue=DDFDRIFT-250
> remove secondary domain, which holbaek doesn't use

- infrastructure/Taskfile.yml
- infrastructure/environments/dplplat01/sites.yaml
Deploy release 2025.3.0 on staging.
Note that this PR also includes a few other changes that are needed before the update can be deployed. This includes:
- Adding a new site for Solrød because a table for the current database has been corrupted
- Removing a call to `lagoon whoami` which currently fails
> Deploy release 2025.3.0 on staging

- infrastructure/environments/dplplat01/sites.yaml
This PR does 5 things
- It releases 2025.3.2 to editors
- Releases 2024.50.0 to webmasters production
- Releases 2025.3.2 to webmaster moduletests
- Removes unused anchors: `postponed-until` as well as `webmasters on default release cycle'
- Introduces the new weekly release cycle as requested by the libraries: https://reload.atlassian.net/browse/DDFDRIFT-277
This should be read thoroughly. Do not apply 
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-283
> Release week 3

- infrastructure/environments/dplplat01/sites.yaml
Updates staging to test release 2025.4.0
Look at it. :)
**Important**: I noticed that the module test version of the staging site were behind the "master" version. Is that a coincidence or do we have to do any further actions - or skip updating the module test version?
> Updating staging to test release 2025.4.0

- infrastructure/environments/dplplat01/sites.yaml
This updates most sites to the latest release 2025.4.0.
Moduletest sites for webmasters are also updated to the latest release while webmaster sites on the weekly schedule are updated to the second most recent release, 2024.3.2.
This has *not* been applied yet.
Read it through.
> Deploy release 2025.4.0

- infrastructure/environments/dplplat01/sites.yaml
It restores CMS-school
Just read it - it has been run already 
https://reload.atlassian.net/browse/DDFDRIFT-288
> add autogenerate (deafult) routes to cms-school

- infrastructure/environments/dplplat01/lagoon/lagoon-remote-values.template.yaml
- infrastructure/environments/dplplat01/sites.yaml
It release 2025.6.0 to: 
- editors
- webmaster moduletest
It also releases 2025.5.1:
- webmaster production 
Additionally cms-school is now tracking the newest release on both prod and moduletest
jsut read it 
Just read it 
DDFDRIFT-303
> Release week 6

- infrastructure/Taskfile.yml
Stabilize the synchronization process from main to module test environments for webmaster sites.
Practice shows there have been a number of problems with the synchronization process. This primarily seems to be caused by idle timeouts in the SSH connection to Lagoon combined with large amount of files which needs to be transferred causing the process to stop. This is combined with the error handling which in the current setup just means that we continue with the next site.
To address this this PR does three things:
1. Split the process into individual task/`lagoon ssh` commands to limit the scope
2. Exclude generated files form the synchronization process to reduce the amount of data that needs to be synchronized
3. Change error handling to abort execution if commands fail.
Try running the …
> Stabilize moduletest environment synchronization for webmaster sites

- infrastructure/environments/dplplat01/lagoon/lagoon-remote-values.template.yaml
- infrastructure/environments/dplplat01/sites.yaml
It releases the newest version to: 
- editor production sites
- webmaster moduletest sites
Webmaster production sites are getting last weeks release on their production sites. 
Herning wants to stay on 5.1 on their production site. 
Deploy 10 sites at a time 
Just read it 
Just read it 
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-305
> Release week 7

- infrastructure/environments/dplplat01/sites.yaml
This PR release version 8.0 to editors and moduletest sites and 7.1 to webmaster production sites
Just read it. It has not been applied yet.
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-306
> release version 8.0 to editors and moduletests and 7.1 to WM prod

- infrastructure/environments/dplplat01/sites.yaml
Deploy release 2025.8.1 to staging. This has already been applied.
The deployment required an extra fix to `sites.yaml` that needs to be merged to get deployments working.
Just read it.
> Deploy release 2025.8.1 to staging

- infrastructure/environments/dplplat01/sites.yaml
This PR releases the following versions to the following environments:
- 9.0 to editors and WM moduletest
- 8.1 to WM production
Just read it 
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-309
> release 9.0 to moduletests and editors and 8.1 to WM prod

- docs/runbooks/weekly-release-to-editors-and-moduletests.md
- infrastructure/environments/dplplat01/sites.yaml
Deploy release 2025.10.0 to editor libraries and moduletest envs, 2025.9.0 to the main env on webmaster libraries.
And fix quoting in runbook (which is out of date, but that's another thing).
> Release 2025.10.0

- infrastructure/Taskfile.yml
Do not set task directory when ensuring project
On OSX even within the DPLSH we sometimes see the following error when running deployments: No Taskfile found at "/home/dplsh/host_mount/environments/dplplat01"
There is no Taskfile in the provided directory and it is not intentional that we execute tasks from this directory either.
For unknown reasons we currently set the default directory to .dir_env which is /home/dplsh/host_mount/environments/dplplat01. This should not be necessary.
The only command which references a specific part of the file system is the SITE_PLAN var. This already uses .dir_env.
Consequently we remove it.
Try to deploy e.g. `SITE=canary task site:full-sync`. It should run without problems.
I have tried to use this during the release of `2025.8.1`. The problem did not …
> Do not set task directory when ensuring project

- infrastructure/environments/dplplat01/sites.yaml
This fixes the newly added anchor, which had disallowed syntax
Just read it
> it is not allowed to use dot in yaml anchor

- infrastructure/environments/dplplat01/sites.yaml
Deploy release 2025.11.0 to webmasters and canary sites. Release 2025.10.0 has a serious bug that we want to avoid.
> Avoid release 2025.10.0

- docs/maintenance-plan.md
Here's an initial take on a maintenance plan. We can make edits to this as we become more knowledgeable on each of the tools. 
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-49
> Add initial maintenance plan

- infrastructure/Taskfile.yml
- infrastructure/task/scripts/lagoon-get-backup.sh
Add task to restore database - potentially across projects/environments. This scripts [the process described in the documentation](https://danskernesdigitalebibliotek.github.io/dpl-docs/DPL-Platform/runbooks/retrieve-restore-backup/?h=retrie#step-1-downloading-the-backup).
1. Create a PR environment for `dpl-cms`.
2. Try to synchronize the database of a site into this environment. 
My results:
```
dplsh:/home/dplsh/host_mount$ SOURCE_PROJECT=kobenhavn TARGET_PROJECT=dpl-cms TARGET_ENV=pr-1956 task site:backup:restore:db
task: Task "_infra:terraform:init" is up to date
task: Task "cluster:auth" is up to date
task: Task "_infra:terraform:init" is up to date
task: Task "cluster:auth" is up to date
task: Task "lagoon:cli:config" is up to date
Restore latest database backup from kobenhavn-main …
```
> Add task to restore database - potentially across projects/environments

- .github/workflows/lagoon-redeploy-controller-build-release.yaml
We were pointing to the old folder, where the project started it's residence. 
It now lives in `infrastructure/images/lagoon-redeploy-controller`
Read it through
> point to the new folder instead

- infrastructure/dpladm/bin/sync-site.sh
Found out we didn't handle sites in `sites.yaml` not having `hasGo` prop. This resulted in the primary go-subdomain being set. 
This PR fixes this
This can be tested on canary by running `SITE=canary task site:sync` and then going to https://github.com/danishpubliclibraries/env-canary/blob/main/.lagoon.yml#L60
If it works, there should be no domains routing to any services if there's no `hasGo` prop on canary. 
Please read it and test it
https://reload.atlassian.net/browse/DDFDRIFT-323
> Handle sites not having prop has go

- infrastructure/images/moduletest-reset-job/templates/moduletest-reset-job.template.yaml
- infrastructure/images/moduletest-reset-job/values.yaml
This PR add's some stuff which I missed in the previous related PR, namely some renaming.
This PR also adds, very crucially, a version bump to the first real release as well as a complete list of webmaster projects that need moduletest sites reset to their main sites every release.
Just read it. Especially the list of projects to be run on, should be reviewed thoroughly.
https://reload.atlassian.net/browse/DDFDRIFT-264
> Moduletest missed stuff

- docs/runbooks/how-release-a-new-version-for-approval-testing.md
- docs/runbooks/weekly-release-to-editors-and-moduletests.md
- infrastructure/environments/dplplat01/sites.yaml
Reverts danskernesdigitalebibliotek/dpl-platform#661
It does not work in the current version. It outputs the literal name of the anchors instead of the value. It seems to be a problem with yq. I wonder how this ever worked.
> Revert "Sites version variables"

- infrastructure/environments/dplplat01/sites.yaml
This follows the release plan for the first releases this week with patches:
- Most production sites: 2025.17.1
- Webmaster sites get
- Production: 2025.15.2
- Module test: 2025.17.1 
Just read it.
> Release week 18.1

- infrastructure/environments/dplplat01/sites.yaml
Deploy release 2025.17.1 on staging.
> 2025.17.1 on staging

- infrastructure/environments/dplplat01/configuration/mariadb-servers/templates/mariadb-server.template.yaml
- infrastructure/environments/dplplat01/configuration/mariadb-servers/upgrade.sh
- infrastructure/environments/dplplat01/configuration/mariadb-servers/values.yaml
Overall this PR ensures operational reliability by: 
- Increasing InnoDB's memory allowance
- assigning DB workloads to autoscaled nodes 
- Requesting more CPU and memory per DB
- setting allows connections to 300 (might increase later)
- telling livenessProbe and readinessProbe wait longer
- labelling the DB workloads as critical, thus disallowing Kubernetes killing them to allocate workloads
Just read it 
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?label=MariaDB&selectedIssue=DDFDRIFT-347
> Adjustments to mariadb server values

- infrastructure/environments/dplplat01/sites.yaml
Deploy versions 2025.21.2 and 2025.20 to sites.
This PR includes a change related to #690 as we need to keep the autogenerated routes available on some sites.
Just read it.
> Release week 21

- infrastructure/environments/dplplat01/sites.yaml
Deploys cms ver. 2025.22.0 and Go 0.25.13 for go-pilots/bnf
Created defaults for go pilots and the BNF site so it is easier to maintain.
> Deploy cms ver. 2025.22.0 and Go 0.25.13 for go-pilots/bnf

- infrastructure/images/moduletest-reset-job/Dockerfile
- infrastructure/images/moduletest-reset-job/moduletest-reset-job.mjs
- infrastructure/images/moduletest-reset-job/templates/moduletest-reset-job.template.yaml
- infrastructure/images/moduletest-reset-job/upgrade.sh
This PR is an improvement upon the last iteration. The main improvement here is the use of underlying tools, which Lagoon also uses, but which for some reason keeps breaking or stop working for us. 
This can be tested by firstly, removing all sites from `value.yaml` but canary or customizable. Then add an image to the main site. Run the `Job` and check moduletest for the image. It hsould be there. 
> Improve moduletest reset job

- infrastructure/dpladm/bin/sync-site.sh
Remove the parameters that make a GO site in moduletest environments
This can be tested on customizable canary by running `SITE=customizable-canary task site:sync` 
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-367
> we do not want a GO site on moduletest

- infrastructure/task/scripts/promote-workloads-to-prod-nodes.sh
We've added some sites which we haven't added the list of workloads which are promoted to run on production nodes. 
With GO we're also adding a node workload which should also be scheduled to run on production nodes
Just read it
> add sites and workloads which should run on prod nodes

- docs/runbooks/add-library-site-to-platform.md
- docs/runbooks/how-release-a-new-version-for-approval-testing.md
Adds documentation of how to release a new Go version.
> Adding how to release a new Go version

- gitops/dplplat01/mariadb-test-prometheus-exporter/Chart.yaml
I was missing the dependency to the Helm chart
> add dependency to community chart

- infrastructure/dpladm/bin/dpladm-shared.source
This fixes moduletests thinking they should have a GO project. 
The reason: Mixed up sequence of arguments/parameters
> Fix correct argument/parameter sequence

- infrastructure/Taskfile.yml
Since the rsync cmd syncs both files and module files we need to make sure that module sub css/js directories are preserved.
> Make sure that css and js dirs are rsynced as well

- gitops/dplplat01/argo-cd-resources/templates/projects/moduletest-reset.yaml
- gitops/dplplat01/argo-cd-resources/values.yaml
- gitops/dplplat01/moduletest-reset/Chart.yaml
- gitops/dplplat01/moduletest-reset/templates/moduletest-reset-cronjob.template.yaml
- gitops/dplplat01/moduletest-reset/values.yaml
This PR moves the moduletest-reset'er into argo cd in it's current state.
The final goal is to have it added to a sort of default `Chart`. This however takes some tuning of the application which hasen't been done yet
> Add moduletest reset to argo

- gitops/dplplat01/ingress-nginx/Chart.yaml
- infrastructure/Taskfile.yml
- infrastructure/environments/dplplat01/configuration/versions.env
This PR removes Tasks and Task related information on how to manage Ingress-Nginx as it has now been moved into Argo CD and will now be managed through Argo. 
The PR is missing a modification to the runbook on how to upgrade Ingress-Nginx
> Clean up after moving ingress nginx

- infrastructure/environments/dplplat01/sites.yaml
Deploy Go release 2025.36.2 to all sites currently on 2025.36.1.
No.
Just read it.
> Deploy Go release 2025.36.2 to all sites currently on 2025.36.1

- infrastructure/environments/dplplat01/sites.yaml
Update all Go sites with hotfix.
> Deploy Go hotfix 2025.38.1 and 2025.36.3 to production/webmaster

- infrastructure/task/scripts/patch-lagoon-env-with-db-connection-info.mjs
This PR patches the `lagoon-env` configMap. This is done because Lagoon's prebackuppod uses the environemnt variables in the configMap to configure the bacukpod to connect to the database that need backup'ing. 
This can be tested safely for now, by running this script. 
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-475
> Patch lagoon env with internal db conn info

- infrastructure/environments/dplplat01/sites.yaml
Deploy 2025.40.0 to staging and bnf moduletest. It has been applied.
Remove `moduletest-php-version` from staging, as both main and moduletest now needs 8.3 and are covered by the `php-version`.
Remvoe the same from bnf as `x-defaults` defines the proper version for both branches now.
> Deploy 2025.40.0 to staging

- infrastructure/environments/dplplat01/sites.yaml
- Pin København and Herning production and Go to 2025.36.x due to DDFSAL-419.
- Unpin Kerteminde and Odense.
- Upgrade production, moduletest and Go sites to  2025.40.x (2 for CMS, 0 for go).
- Upgrade webmaster production to 2025.38.x
- Upgrade København and Herning moduletest to 2025.40.x.
> Release 2025.40.x

- gitops/dplplat01/moduletest-reset/templates/moduletest-reset-cronjob.yaml
- infrastructure/images/moduletest-reset-job/moduletest-reset-job.mjs
This PR does a couple of things
- It drops the tables of the database before importing the new one from main
- Now tells us if it is using the override variables 
- Gets the database host from the service
> When resetting db drop it first

- infrastructure/Taskfile.yml
- tools/dplsh/Dockerfile
I suggest to remove cert-manager-verifier from DPLSH because we're not using it. Removing it will also make it easier to get out DPLSH down the road - and for good measure: less code is better
> remove cert-manager-verifier
