.github/PULL_REQUEST_TEMPLATE.md, .markdownlint-cli2.yaml, documentation/runbooks/upgrading-lagoon.md, infrastructure/.dplsh.profile, infrastructure/README.md, infrastructure/Taskfile.yml, tools/dplsh/README.md
We're doing the first major Lagoon and documenting the process as we go along.
The upgrade is being done as a collaborative effort, so reviewing is done on the fly.
DDFDPDEL-206
=> Upgrade lagoon and document the procedure

documentation/runbooks/add-generic-site-to-platform.md, documentation/runbooks/add-library-site-to-platform.md, documentation/runbooks/upgrading-aks.md, infrastructure/README.md, infrastructure/Taskfile.yml, infrastructure/environments/dplplat01/configuration/grafana/grafana-values.yaml, infrastructure/environments/dplplat01/configuration/loki/loki-values.template.yaml, infrastructure/environments/dplplat01/configuration/minio/minio-values.template.yaml, infrastructure/environments/dplplat01/configuration/promtail/promtail-values.yaml, infrastructure/environments/dplplat01/configuration/versions.env, infrastructure/environments/dplplat01/infrastructure/main.tf, infrastructure/task/scripts/util.source.sh, infrastructure/terraform/modules/dpl-platform-environment/aks.tf, infrastructure/terraform/modules/dpl-platform-environment/dnsimple.tf, infrastructure/terraform/modules/dpl-platform-environment/outputs.tf, infrastructure/terraform/modules/dpl-platform-environment/providers.tf, infrastructure/terraform/modules/dpl-platform-environment/storage_backup.tf, infrastructure/terraform/modules/dpl-platform-environment/storage_harbor.tf, infrastructure/terraform/modules/dpl-platform-environment/storage_lagoon.tf, infrastructure/terraform/modules/dpl-platform-environment/variables.tf
The original goal of this change was to upgrade AKS, but due to some problems with the Terraform provider I ended up rebuilding the entire environment.
As I had to rebuild the entrie cluster, and as we do not have any other environements, I took the chance to upgrade all support projects as well.
You will have to go through all the commits. I've split them up into the individual changes for easier review.
DDFDPDEL-212
=> General upgrade of AKS and all support projects

documentation/runbooks/access-kubernetes.md, infrastructure/Taskfile.yml
Improve documenation for accessing Kubernetes.
There are a number of steps/rrerequisites which only needs to be setup once and are thus easy to forget. Let's document them!
Good question. I bet you do not want to reset your entire development environment for this so I guess a sanity check is OK.
=> Improve Kubernetes access docs

documentation/runbooks/access-kubernetes.md
=> Document az auth better

tools/dplsh/Dockerfile, tools/dplsh/Taskfile.yml, tools/dplsh/dplsh.sh, tools/dplsh/files/dplsh-entrypoint.sh
Fix the ownership of the files the entrypoint rsyncs.
This required a change where the entrypoint now runs as root, but drops privilegeds when it is done with its work.
Do a local build of dplsh and see if you can start it.
=> Fix the ownership of the files the entrypoint rsyncs into the container.

docs/runbooks/upgrading-support-workloads.md, infrastructure/Taskfile.yml, infrastructure/environments/dplplat01/configuration/versions.env, infrastructure/task/scripts/ui-password.sh
Adds documentation on how to upgrade all our support workloads.
I've upgraded most workloads to one patch-version below the latest. So, go through the documentation and carry out the upgrade of each workload following the documentation.
=> Add documentation for how to upgrade all remaining support workloads.

docs/runbooks/upgrading-support-workloads.md, infrastructure/.gitignore, infrastructure/environments/dplplat01/configuration/ingress-nginx/ingres-nginx-values.template.yaml, infrastructure/environments/dplplat01/configuration/versions.env, infrastructure/environments/dplplat01/lagoon/lagoon-versions.env
This PR mainly commits changes to versions of the support workloads and Lagoon itself in the platform cluster.
The changes shown here are already live.
=> Upgrade Lagoon and support workloads

infrastructure/dpladm/env-repo-template/standard/.lagoon.yml, infrastructure/environments/dplplat01/sites.example.yaml, infrastructure/environments/dplplat01/sites.yaml
* Adds the pilot sites to sites.yml
* Renames former sites.yml to sites.example.yml
* Adds translation import to cron job
You can see the sites in the lagoon interface.
Look at commits.
https://reload.atlassian.net/browse/DDFLSBP-435
=> Pilot sites

infrastructure/dpladm/env-repo-template/standard/.lagoon.yml
=> Make sure that config translations are added as a part of the roll out

infrastructure/dpladm/env-repo-template/standard/.lagoon.yml, infrastructure/environments/dplplat01/sites.yaml
- Ensures ssh and api configs for all sites are set correctly to point to our infrastructure
- Deploys dpl-cms@2024.15.1 to all pilot sites
I have *not* run these changes yet. They are ready to be run thursday April 11th at 3pm
Do the changes look reasonable?
[DDFDRIFT-68](https://reload.atlassian.net/browse/DDFDRIFT-68?atlOrigin=eyJpIjoiMzE3MGFkNmM5YjY2NDg1Y2E4ZTMwOGYzZTg4MjI2OTAiLCJwIjoiaiJ9)
[DDFDRIFT-68]: https://reload.atlassian.net/browse/DDFDRIFT-68?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Release 2024.15.1

infrastructure/dpladm/env-repo-template/standard/.lagoon.yml
=> Revert to backing up once per day

docs/architecture/performance-strategy.md, docs/runbooks/README.md, docs/runbooks/connecting-the-lagoon-cli.md, docs/runbooks/remove-site-from-platform.md, docs/runbooks/retrieve-restore-backup.md, docs/runbooks/scale-aks.md, docs/runbooks/using-dplsh.md
While working on #246 I looked through all guides and runbooks to ensure they were correct after the changes. I also found these minor things I thought it was worth correcting.
Read the documentation changes and ensure that each document makes sense now.
N/A
=> Guide updates

infrastructure/dpladm/env-repo-template/standard/.lagoon.yml
It sets the backup schedule to run at 12.00 and 00.00 hours. 
no, it is thouroughly tested before being sent to review
no
https://reload.atlassian.net/browse/DDFDRIFT-35
=> run backup at 12.00 and 00.00

infrastructure/Taskfile.yml, infrastructure/environments/dplplat01/lagoon/lagoon-remote-values.template.yaml, infrastructure/terraform/modules/dpl-platform-environment/communication_services.tf, infrastructure/terraform/modules/dpl-platform-environment/outputs.tf
This PR adds a mailing service
This PR can be tested by running the following comand in dpl shell: 
`PROJECT_NAME=struer task lagoon:project:ensure:azure-mail-connection-string` and check that the variable has been set. It's possible to view the value of the variable by pressing "show values" 
Please test it on fx. the struer project
https://reload.atlassian.net/browse/DDFDRIFT-60
=> Provision mail services

infrastructure/dpladm/env-repo-template/standard/lagoon/conf/nginx/location_prepend_drupal_authorize.conf, infrastructure/dpladm/env-repo-template/standard/lagoon/conf/nginx/server_append_drupal_authorize.conf, infrastructure/dpladm/env-repo-template/standard/lagoon/conf/nginx/server_append_drupal_modules_local.conf, infrastructure/dpladm/env-repo-template/standard/lagoon/conf/nginx/server_append_drupal_rewrite_registration.conf, infrastructure/dpladm/env-repo-template/standard/lagoon/nginx.dockerfile
Adds nginx conf
For upload of modules for webmaster sites and for redirect of old registration url too new one.
https://reload.atlassian.net/browse/DDFLSBP-608
=> Add nginx conf

infrastructure/Taskfile.yml, infrastructure/environments/dplplat01/sites.yaml
It add's all the sites that Peter gave us. The new sites has not yet been initialized, thus they have no deployKeys. 
This PR should be read through carefully, but not tested - testing can't be done with out making the sites go live
Please read it carefully - especially the sites that already exists should be noted. Some of the preexisting sites has had their descriptions changed. 
https://reload.atlassian.net/browse/DDFDRIFT-75
=> Add all the libraries we got from Peter to sites.yaml file. 

infrastructure/environments/dplplat01/configuration/harbor/harbor-values.template.yaml
- Scale harbor core and registry now that we have more data going through the systems (already executed in cluster)
- ...?
This PR is a draft that @achton can extend when trying to scale up our harbor installation.
[DDFDRIFT-96](https://reload.atlassian.net/browse/DDFDRIFT-96?atlOrigin=eyJpIjoiNmRkNTE4NmE1ZWIxNDlkYzkxZTIzOGNjZTQ0NTkxMDciLCJwIjoiaiJ9)
[DDFDRIFT-96]: https://reload.atlassian.net/browse/DDFDRIFT-96?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Scale Harbor

infrastructure/environments/dplplat01/configuration/ingress-nginx/ingres-nginx-values.template.yaml
Sets up autoscaling for the ingress controller. May help with load times on site pages.
[DDFDRIFT-96](https://reload.atlassian.net/browse/DDFDRIFT-96?atlOrigin=eyJpIjoiNmRkNTE4NmE1ZWIxNDlkYzkxZTIzOGNjZTQ0NTkxMDciLCJwIjoiaiJ9)
[DDFDRIFT-96]: https://reload.atlassian.net/browse/DDFDRIFT-96?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Scale ingress controller with autoscaler

infrastructure/environments/dplplat01/sites.yaml
Releases 2024.18.0 to all sites
In the heat of battle we forgot to release this - sorry 😦 It'll go out first thing in the morning!
[DDFDRAFT-75](https://reload.atlassian.net/browse/DDFDRIFT-75?atlOrigin=eyJpIjoiOWZkZGViM2YxZmNlNDA0YWE1MWI3ODdlMzhmMGExZjciLCJwIjoiaiJ9)
=> Release 2024.18.0 to all sites

infrastructure/environments/dplplat01/sites.yaml
Does what it says on the tin.
[DDFDRIFT-99](https://reload.atlassian.net/browse/DDFDRIFT-99?atlOrigin=eyJpIjoiMjE0ZGRiMGU1YjMyNDM0MDgwZDZmNGVlMDBmZTE3ZmUiLCJwIjoiaiJ9)
[DDFDRIFT-99]: https://reload.atlassian.net/browse/DDFDRIFT-99?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Release 2024.18.3 to canary and cms-school for testing

infrastructure/dpladm/autoscaler.template.yaml, infrastructure/environments/dplplat01/sites.yaml
What the title says.
Has been executed in the platform.
[DDFDRIFT-96](https://reload.atlassian.net/browse/DDFDRIFT-96)
[DDFDRIFT-96]: https://reload.atlassian.net/browse/DDFDRIFT-96?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Removes lemvig,slagelse,tonder who are not going to use the platform

infrastructure/environments/dplplat01/sites.yaml
This tests how primary- and secondary domains work. In preparation for go-live with Herlev and Billund. Serves as a proof of concept that it works.
Has been executed and is live (and HTTPS works etc):
- https://bibliotest.deranged.dk/
- https://www.bibliotest.deranged.dk/
[DDFDRIFT-97](https://reload.atlassian.net/browse/DDFDRIFT-97?atlOrigin=eyJpIjoiMzQzY2UyNGMyOGM3NDU0Zjg0OTdlZjVhMDM3YTRmOGUiLCJwIjoiaiJ9)
[DDFDRIFT-97]: https://reload.atlassian.net/browse/DDFDRIFT-97?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Testing primary and secondary domains on canary

infrastructure/environments/dplplat01/sites.yaml
=> roll out 2024.19.0 out on all sites

infrastructure/environments/dplplat01/sites.yaml
This PR does what it says on the tin
=> rollback herning to 2024.19.0

tools/dplsh/Dockerfile
This PR upgrades the Azure CLI to 2.61.0, which supports the actions we need to run on `communication`
Just read it through. Maybe try and run a command to get something from Azure throug it: https://learn.microsoft.com/en-us/cli/azure/communication/email/domain/sender-username?view=azure-cli-latest#az-communication-email-domain-sender-username-create
None
=> upgrade az cli

infrastructure/environments/dplplat01/configuration/loki/loki-values.template.yaml
Fixes loki helm chart config (some lines had no effect), and changes retention period to 30 days.
Run the diff and verify that it makes sense.
[DDFDRIFT-109](https://reload.atlassian.net/browse/DDFDRIFT-109)
[DDFDRIFT-109]: https://reload.atlassian.net/browse/DDFDRIFT-109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix loki retention

infrastructure/environments/dplplat01/sites.yaml
=> Deploy release 2024.23.0 to canary and CMS school

infrastructure/environments/dplplat01/sites.yaml
This PR sets routes for Herning
This should be read through and the routes should be checked by typing in the urls and looking to se what url redirects to which, thus ensuring that the correct primary and secondarydomains has been set
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-140
This has been run
=> Herning - go live

infrastructure/environments/dplplat01/sites.yaml
This PR rolls out 2024.23.0 to every every library
Read it through. It has already been run
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-137
=> Release 2024.23.0 

infrastructure/environments/dplplat01/sites.yaml
This PR allows Samsø to go live
**This has been run**
Read it throug
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-145
=> add domains for samsø

infrastructure/environments/dplplat01/configuration/cert-manager/cert-manager-values.yaml
This PR allows cert manager to handle more concurrent challenges 
Read it through 
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-145
=> Up cert manager max challenges

infrastructure/environments/dplplat01/sites.yaml
This PR sets routes for Kobenhavn
This should be read through and the routes should be checked by typing in the urls and looking to se what url redirects to which, thus ensuring that the correct primary and secondarydomains has been set
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-141
This has been run
=> Kobenhavn - go live

infrastructure/environments/dplplat01/sites.yaml
Does what it says on the tin
Just read it through - it has been run
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-149
=> make a webmaster for cms school

infrastructure/environments/dplplat01/sites.yaml
This PR sets routes for Allerod. 
This should be read through and the routes should be checked by typing in the urls and looking to se what url redirects to which, thus ensuring that the correct `primary` and `secondary`domains has been set
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-139
=> Go live - allerod

infrastructure/environments/dplplat01/sites.yaml
This PR changes the default release to 2024.24.0
**This has been run**
Just read it
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-158
=> change release to 2024.24.0

infrastructure/Taskfile.yml
I had some some stuff in a prior MR, which I haden't corrected, thus this PR.
Yes - please read it through. It can be tested on canary og cms school
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-136
=> Fixes to admin role task

infrastructure/environments/dplplat01/sites.yaml
It sent Hørsholm live on DPL CMS
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-160
=> sent horsholm live

infrastructure/environments/dplplat01/sites.yaml
Deploy 2024.25.0 on canary. This has already been executed.
=> Deploy 2024.25.0 on canary

infrastructure/environments/dplplat01/sites.yaml
This PR sends the libraries that should go live 19.06.2024 live. Here's the list: https://reload.zulipchat.com/#narrow/stream/435665-DDF---Drift.2B/topic/Uge.2025.20.2E14.20biblioteker.20g.C3.A5r.20i.20drift/near/445312634
Read it though. Test some of the urls are correct and i fact secondary and primary domains
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-161
=> Go live 19.06.24

infrastructure/environments/dplplat01/infrastructure/main.tf
Does what it says on the tin
Just read it
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-96
=> up the min number of nodes for the app pool to 11

infrastructure/environments/dplplat01/sites.yaml
This PR adds routes to Hillerød. **This has been run!!!**
Read it through - test the domains and ensure the primary and secondary domains have been add'ed correctly
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-165
=> add hillerød

infrastructure/environments/dplplat01/sites.yaml
does what it says on the tin.
**This has been run**
Just read it
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-166
=> Release 2024.25.1

infrastructure/environments/dplplat01/infrastructure/main.tf
Does what it says on the tin. This has been run unsuccesfully, as the quotas for vm and CPU's needs a bump. The Azure support has been contacted and I'm awaiting them. It's fine to approve this, but do not merge it - let me handle that. 
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-167
=> Create new nodepool with E-class VM's

infrastructure/environments/dplplat01/sites.yaml
Sets up domains for libraries going live 24th of June 2024
Has already been executed in the infrastructure.
[DDFDRIFT-168](https://reload.atlassian.net/browse/DDFDRIFT-168)
[DDFDRIFT-168]: https://reload.atlassian.net/browse/DDFDRIFT-168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Set up domains going live 24th of June 2024

infrastructure/Taskfile.yml, infrastructure/environments/dplplat01/sites.yaml
Sets up domains for sites going live 25th of June 2024.
Has been executed in the infrastructure.
[DDFDRIFT-169](https://reload.atlassian.net/browse/DDFDRIFT-169)
[DDFDRIFT-169]: https://reload.atlassian.net/browse/DDFDRIFT-169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Added domains going live 25th of June 2024

infrastructure/environments/dplplat01/sites.yaml
What it says
[DDFDRIFT-169](https://reload.atlassian.net/browse/DDFDRIFT-169)
[DDFDRIFT-169]: https://reload.atlassian.net/browse/DDFDRIFT-169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Swap www. and non-www. viborg domains

infrastructure/environments/dplplat01/sites.yaml
Sets up domains for libraries going live June 26th
[DDFDRIFT-170](https://reload.atlassian.net/browse/DDFDRIFT-170)
[DDFDRIFT-170]: https://reload.atlassian.net/browse/DDFDRIFT-170?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Go live 26.06.2024

infrastructure/environments/dplplat01/sites.yaml
What it says on the tin.
Has been executed in infra.
Read through: does it look right at a glance?
[DDFDRIFT-171](https://reload.atlassian.net/browse/DDFDRIFT-171)
[DDFDRIFT-171]: https://reload.atlassian.net/browse/DDFDRIFT-171?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Set up domains for libraries going lvie June 27th 2024

infrastructure/environments/dplplat01/sites.yaml
Releases latest version everywhere
Also adds a new site for testing for the libraries.
[DDFDRIFT-173](https://reload.atlassian.net/browse/DDFDRIFT-173)
[DDFDRIFT-173]: https://reload.atlassian.net/browse/DDFDRIFT-173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Release 2024.27.1

infrastructure/environments/dplplat01/sites.yaml
adds a missing deploykey and removes a url
=> add deploy key and remove a url

infrastructure/environments/dplplat01/sites.yaml
=> Deploy 2024.28.0 to canary

infrastructure/environments/dplplat01/sites.yaml
=> Release 2024.28.0

docs/runbooks/changing-and-releasing-new-dplsh-version.md
… dplsh
This PR adds a runbook which explains how to update the dplsh. 
If you have something that need updating - try it out. Otherwise read it through.
=>  runbook for updating and releasing a new version of dplsh

infrastructure/environments/dplplat01/sites.yaml
This has already been applied in production.
=> Deploy release 2024.29.0 on Canary

tools/dplsh/Dockerfile
=> upgrade lagoon cli to 0.23.1

infrastructure/environments/dplplat01/sites.yaml
Update sites to release 2024.29.1.
This has already been applied to production.
=> Release 2024.29.1

infrastructure/environments/dplplat01/sites.yaml
It adds Odsense to the webmater plan
Just read it
=> put Odense on the webmaster plan

infrastructure/environments/dplplat01/sites.yaml
Increases from 29.1 => 32.1
Read it through
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-182
=> update version to 32.1

infrastructure/environments/dplplat01/sites.yaml
Exactly what it says it does
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-182
=> we also need to bump the webmasters to 32.1

infrastructure/environments/dplplat01/sites.yaml
Does what it says on the tin
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-185
=> add gentofte's urls so they can go live

infrastructure/environments/dplplat01/sites.yaml
It releases 33.0 to all sites but the webmaster libraries, as 4 weeks hasn't passed since their last update
Read it through
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-186
=> release 2024.33.0

infrastructure/environments/dplplat01/sites.yaml
It add's primary and secondary routes, so the libraries can go live
The libraries are the ones mentioned here: https://reload.zulipchat.com/#narrow/stream/435665-DDF---Drift.2B/topic/Udrulning.20uge.2035.20-.20en.20lille.20.C3.A6ndring/near/465545830
Read it through test the urls are correct in your browser
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-201
=> Go live 28/8

infrastructure/environments/dplplat01/lagoon/lagoon-remote-values.template.yaml
It attempts to increase the speed of deployments by allowing more consecutive builds to made
Just read it through
DDFDRIFT-184
=> attemp to increase deployment speed

infrastructure/environments/dplplat01/sites.yaml
=> Deploy 2024.37.0 to Canary

infrastructure/task/scripts/adjust-resource-requests.sh
It let's us set the resource request of pod (via deployment) more precisely. 
You can, but it has been run
read and maybe run it 
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-200
=> set resource request by type of deployment

infrastructure/environments/dplplat01/configuration/grafana/grafana-values.yaml, infrastructure/environments/dplplat01/configuration/prometheus/prometheus-values.yaml
Adds tolerations and affinity to grafana
86
=> Add tolerations and affinity to grafana

infrastructure/environments/dplplat01/configuration/prometheus/prometheus-values.yaml
Adds tolerations and affinity for prometheus workloads
86
=> Set tolerations and affinity for prometheus

infrastructure/environments/dplplat01/lagoon/lagoon-remote-values.template.yaml
Assigns lagoon-remote workloads to system nodes
No
No
DDFDRIFT-86
=> Assign lagoon-remote workloads to system nodes

infrastructure/environments/dplplat01/configuration/harbor/harbor-values.template.yaml
It should make Kubernetes schedule Harbor on our system nodes 
No
Read it throug
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-86
=> Add tolerations and affinity to harbor

infrastructure/environments/dplplat01/configuration/k8up/k8up-values.template.yaml
Adds affinity and tolerations for k8up workloads
86
=> Add affinity and tolerations for k8up workloads

infrastructure/environments/dplplat01/configuration/loki/loki-values.template.yaml
Adds affinity and tolerations for loki workloads
86
=> Add affinity and tolerations for loki workloads

infrastructure/environments/dplplat01/lagoon/lagoon-core-values.template.yaml
Add affinity and tolerations to lagoon core 
no
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-86
=> Add tolerations and affinity to lagoon core

infrastructure/environments/dplplat01/sites.yaml
Deploy release 2024.38.2 on Canary.
=> Deploy release 2024.38.2 on Canary

infrastructure/environments/dplplat01/sites.yaml
Add missing properties
just Read it
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-227
=> add missing properties

infrastructure/environments/dplplat01/sites.yaml
Deploy 2024.39.1 to all default and webmaster moduletest sites
=> Rollout 2024.39.1

infrastructure/environments/dplplat01/sites.yaml
It sets Frederiksberg live
Just read it
Just read it
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-231
=> Go live frederiksberg

docs/runbooks/reset-moduletest.md
It describes how to reset a moduletest site
Read it through. You can test it on canary
read and test it 
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-206
=> instructions on how to reset a moduletest site

infrastructure/environments/dplplat01/sites.yaml
It does what it says on the tin. 
REquest: https://reload.zulipchat.com/#narrow/stream/435665-DDF---Drift.2B/topic/Aalborg.20.C3.B8nsker.20at.20blive.20opgraderet.20hver.20uge
Read it
No
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-235
=> aalborg wants weekly releases on their production environment

infrastructure/environments/dplplat01/sites.yaml
Deploy release 2024.40.0 to Canary.
=> Deploy release 2024.40.0 to Canary

infrastructure/environments/dplplat01/sites.yaml
Deploy release 2024.41.1 to Canary.
=> Deploy release 2024.41.1 to Canary

infrastructure/environments/dplplat01/sites.yaml
Deploy release 2024.43.0 to Canary.
=> Deploy release 2024.43.0 to Canary

infrastructure/environments/dplplat01/sites.yaml
Release 43.0 to editor, webmaster moduletest sites and webmasters with weekly releases.
No
Read it
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-243
=> Release 43.1

infrastructure/environments/dplplat01/configuration/versions.env
It reflects the updated version
no
just read it
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-242
=> we have now upgraded Cert-manager to 1.15.3

infrastructure/environments/dplplat01/configuration/versions.env
It upgrades Grafana chart to 8.1.0
no
just read it
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-242
=> upgrade Grafana chart to 8.1.0

infrastructure/environments/dplplat01/sites.yaml
Deploy release 2024.44.0 to Staging.
=> 2024.44.0 on staging

infrastructure/environments/dplplat01/sites.yaml
Deploy release 2024.44.1 on staging.
=> Deploy release 2024.44.1 on staging

docs/runbooks/troubleshoot-release-deployment.md
Add more known types of problems based on experience deploying release 2024.44.1.
Examples:
- https://ui.lagoon.dplplat01.dpl.reload.dk/projects/ringsted/ringsted-main/deployments/lagoon-build-pia22h
- https://ui.lagoon.dplplat01.dpl.reload.dk/projects/frederiksberg/frederiksberg-main/deployments/lagoon-build-79ouyy
This cannot really be tested.
=> Add more known types of problems during deployments

infrastructure/environments/dplplat01/sites.yaml
Sæt holbæk live
just read it 
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-250
=> add holbeak routes

docs/runbooks/monthly-release-to-editors-and-webmasters.md
It ensures that the steps taken to make  the monthly webmater production release update is done in the right sequence.
OBS. one step mentions a task that I haven't made yet, but will make after this.
Just read it
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-232
=> rework the monthly deploy guide

infrastructure/environments/dplplat01/sites.yaml
Deploy release 2024.45.0 on staging.
=> Deploy release 2024.45.0 on staging

infrastructure/environments/dplplat01/sites.yaml
Deploy release 2024.46.0 on staging.
=> Deploy release 2024.46.0 on staging

infrastructure/environments/dplplat01/sites.yaml
Release 45.0 to editors and moduletests
Read it
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-254
=> release 45.0 to editors and moduletests

infrastructure/environments/dplplat01/sites.yaml
Deploy release 2024.47.1 on staging.
=> Deploy release 2024.47.1 on staging

infrastructure/environments/dplplat01/sites.yaml
Tilføj Torshavn som det første Færørske bibliotek
Just read it - it has been applied 
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-261
=> Add torshavn library

infrastructure/environments/dplplat01/sites.yaml
Deploy release 2024.48.0 on staging.
=> Deploy release 2024.48.0 on staging

infrastructure/environments/dplplat01/sites.yaml
For the moment this is an estimation of what domains are appropriate for the site.
The actual set of domains should be verified later on.
The current version [fcab14c](https://github.com/danskernesdigitalebibliotek/dpl-platform/pull/530/commits/fcab14cde3ae4abf0ac2540243248a00b7789f00) has been applied.
=> Add domains for Faaborg Midtfyn

infrastructure/environments/dplplat01/sites.yaml
Deploy release 2024.48.1 on staging.
=> Deploy release 2024.48.1 on staging

infrastructure/environments/dplplat01/sites.yaml
Provides Jammerbugt with domains
It should be read
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-268
=> add domains to jammerbugt

infrastructure/environments/dplplat01/sites.yaml
Apply hotfix to fix `modules/local` symlink.
=> Deploy 2024.48.1 hotfix to affected sites

infrastructure/environments/dplplat01/sites.yaml
Sets routes for Aarhus
Just read it 
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-270
=> Go live Aarhus

infrastructure/environments/dplplat01/sites.yaml
=> Deploy release 2024.50.0 on staging

infrastructure/environments/dplplat01/sites.yaml
This adds routes to Kerteminde that matches their current setup
Just read it
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-274
=> add routes to kerteminde library

docs/lagoon-projects.md
Document the difference between Lagoon projects.
=> Add page describing Lagoon projects

infrastructure/environments/dplplat01/sites.yaml
Add routes to Torshavn library. 
They don't have any CAA records, so we should be good go.
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-275
=> add routes to torshavn, which fit their current setup

infrastructure/environments/dplplat01/sites.yaml
Deploy release 2025.2.0 on staging.
No
No
=> Deploy release 2025.2.0 on staging

infrastructure/environments/dplplat01/configuration/cert-manager/cert-manager-values.yaml
It increases the number of concurrent challenges Cert-manager will accept to handle 
No it has been implemented 
Just read it
DDFDRIFT-280
=> up number of concurrent challenges cert-manager will accept

infrastructure/environments/dplplat01/configuration/mariadb-operator/upgrade.sh, infrastructure/environments/dplplat01/configuration/mariadb-operator/values.yaml
Add MariaDB Operator values and helm chart
Nope.
It can be installed directly. Then check the logs, and verify namespace and node allocation.
DDFDRIFT-282
=> Add mariadb operator helm chart and values

infrastructure/environments/dplplat01/sites.yaml
Add routes to Svendborg 
Just read it
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-286
=> add primary and secondary domains to svendborg

infrastructure/environments/dplplat01/sites.yaml
It adds routes to Assens library and fills in the missing version pining for cms-school
read it 
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-289
=> Go live assens

infrastructure/environments/dplplat01/sites.yaml
This adds routes to langeland library
just read it 
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-290
=> Go live langeland

infrastructure/environments/dplplat01/sites.yaml
Deploys release 2025.5.0 to staging
=> Deploying release 2025.5.0 to staging

infrastructure/environments/dplplat01/sites.yaml
Release 2025.5.1
Done have one
=> release 2025.5.1 to staging

infrastructure/environments/dplplat01/sites.yaml
This releases:
- 2025.5.1 to editors and moduletests
- 2025.4.0 to webmaster production sites
Just read it
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-293
=> Release week 5

infrastructure/environments/dplplat01/sites.yaml
Deploy release 2025.6.0 on staging. 
=> Deploy release 2025.6.0 on staging

infrastructure/environments/dplplat01/sites.yaml
Deploy release 2025.7.1 on staging. This has already been applied.
=> Deploy release 2025.7.1 on staging

infrastructure/environments/dplplat01/sites.yaml
Update BNF domians.
This has not been applied yet, waiting for DNS propagation.
=> Update BNF domains

infrastructure/environments/dplplat01/sites.yaml
Deploy release 2025.8.0 on staging.
=> Deploy release 2025.8.0 on staging

infrastructure/environments/dplplat01/lagoon/lagoon-remote-values.template.yaml, infrastructure/environments/dplplat01/sites.yaml
fix to a slight oversigt on my behalf. This adds herning back to the webmaster regular release cycle.
This was added before I ran the deployment so it is in effect.
Just read it 
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-306
=> forgot to point herning at the new release

infrastructure/environments/dplplat01/sites.yaml
Deploy release 2025.9.0 to staging.
Just read it.
=> Deploy release 2025.9.0 to staging

infrastructure/environments/dplplat01/sites.yaml
it updates the CMS-school site to version 10.0. It also moves some lines around.
just read it 
none
=> update cms-school to version 10.0

infrastructure/environments/dplplat01/sites.yaml
Deploy 2025.11.0 to staging. This has already been applied.
Just read it.
=> Deploy release 2025.11.0 to staging

infrastructure/environments/dplplat01/sites.yaml
This is the release plan for this week according to rebekka: [#DDF+ > Release 2025.11.0 @ 💬](https://reload.zulipchat.com/#narrow/channel/419623-DDF.2B/topic/Release.202025.2E11.2E0/near/505122251)
Just read it
=> Release week 11

infrastructure/environments/dplplat01/configuration/cert-manager/cert-manager-values.yaml
This PR should help alleviate the congestions sometimes experience with certificates not being provisioned.
just read it - it has already been applied
none
=> allow more concurrent challenges

infrastructure/images/lagoon-redeploy-controller/Dockerfile, infrastructure/images/lagoon-redeploy-controller/redeploy.sh
This moves the .lagoon.yaml file to where the lagoon cli can find it
Just read it 
=> move the .lagoon.yaml file to where lagoon can find it

.github/workflows/lagoon-redeploy-controller-build-release.yaml, infrastructure/images/lagoon-redeploy-controller/Dockerfile
this is an attempt at having a faster feedback flow while building images for the LRC
=> attempt to have images built upon pr being made

.gitignore
add `kdevconfig.yaml` and `skaffold.yaml` to `.gitignore` 
Not really necessary but you can
Just read it 
=> we don't want to add kdev config and skaffold config to version control

infrastructure/environments/dplplat01/sites.yaml
Deploy release 2025.13.0 to staging.
=> Deploy release 2025.13.0 to staging

infrastructure/environments/dplplat01/sites.yaml
Deploy release 2025.13.1 on staging. This has already been applied.
=> Deploy release 2025.13.1 on staging

infrastructure/environments/dplplat01/sites.yaml
Deploy release 2025.13.1 to all sites currently on 2025.13.0
=> Deploy release 2025.13.1 to all sites currently on 2025.13.0

infrastructure/environments/dplplat01/sites.yaml
=> Deploy release 2025.14.2 on staging

infrastructure/environments/dplplat01/sites.yaml
This updates according to [#DDF - Drift+ > Release uge 14 pt. 2 @ 💬](https://reload.zulipchat.com/#narrow/channel/435665-DDF---Drift.2B/topic/Release.20uge.2014.20pt.2E.202/near/509888801)
Read it throug
=> Release week 14

infrastructure/environments/dplplat01/configuration/mariadb-servers/Chart.yaml, infrastructure/environments/dplplat01/configuration/mariadb-servers/templates/mariadb-server.template.yaml, infrastructure/environments/dplplat01/configuration/mariadb-servers/values.yaml
This PR adds a chart for us to add a mariadb cluster
This can be tested by running `helm template`
test it and review it
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-317&sprint=1117
Toggl: DPL Platform udvikling
=> Prod incluster mariadb 10.6

infrastructure/images/lagoon-redeploy-controller/lagoon-redeploy-controller-job.yaml
It updates the manifest with the newest version of the LRC
No, It has been rolled out
Just read it 
https://reload.atlassian.net/browse/DDFDRIFT-264
=> deploy the new release of the LRC

.github/workflows/moduletest-file-reset-build-release.yaml
Fixes build step id, which is, I think, preventing me from building releases in the correct way 
just read it
=> correction to build step id

infrastructure/environments/dplplat01/sites.yaml
Deploy release 2025.15.0 to staging. This has already been applied.
=> Deploy release 2025.15.0 to staging

infrastructure/environments/dplplat01/sites.yaml
Deploy release 2025.15.1 to staging
=> Deploy release 2025.15.1 to staging

infrastructure/environments/dplplat01/sites.yaml
This deploys the new release according to: [#DDF - Drift+ > Release uge 15 @ 💬](https://reload.zulipchat.com/#narrow/channel/435665-DDF---Drift.2B/topic/Release.20uge.2015/near/511332720)
Read it through
https://reload.atlassian.net/browse/DDFDRIFT-332
=> Release week 15

infrastructure/environments/dplplat01/sites.yaml
This PR updates release according to this: [#DDF - Drift+ > Release uge 17 @ 💬](https://reload.zulipchat.com/#narrow/channel/435665-DDF---Drift.2B/topic/Release.20uge.2017/near/513837042)
just read it 
just read it 
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-336
=> Release week 17

infrastructure/environments/dplplat01/sites.yaml
Deploy release 2025.18.0 to staging. This has already been applied.
=> Release week 18.2

infrastructure/environments/dplplat01/sites.yaml
This PR implements this weeks release plan: [#DDF - Drift+ > Release uge 18 pt. 2 @ 💬](https://reload.zulipchat.com/#narrow/channel/435665-DDF---Drift.2B/topic/Release.20uge.2018.20pt.2E.202/near/515288864)
Just read it 
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-343
=> Release week 18 part 2

infrastructure/environments/dplplat01/sites.yaml
Deploy the the first part of this weeks releases.
Deployment to staging has already been applied.
Just read it.
=> Release week 19.1

infrastructure/environments/dplplat01/sites.yaml
This is the second part of the weekly release:
- Deploy release 2025.19.0 to staging (already applied)
Just read it.
=> Release week 19.2

infrastructure/environments/dplplat01/sites.yaml
Deploy release 2025.20.0 on staging.
=> Deploy release 2025.20.0 to staging

infrastructure/environments/dplplat01/sites.yaml
release according to this plan: [#DDF+ > Release 2025.20.0 @ 💬](https://reload.zulipchat.com/#narrow/channel/419623-DDF.2B/topic/Release.202025.2E20.2E0/near/518066058)
just read it 
just read it 
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-356
=> Release week 20

infrastructure/environments/dplplat01/sites.yaml
This time with actual changes.
=> Deploy release 2025.21.1 to staging

infrastructure/environments/dplplat01/sites.yaml
Deploy release 2025.21.2 on staging.
=> Deploy release 2025.21.2 to staging

infrastructure/Taskfile.yml
Added task to add required drupal next caching env variables.
Read commit message
=> Added task to add required drupal next caching env variables.

infrastructure/dpladm/env-repo-template/standard/.env.defaults, infrastructure/dpladm/env-repo-template/standard/README.md, infrastructure/dpladm/env-repo-template/standard/lagoon/node.dockerfile, infrastructure/environments/dplplat01/sites.yaml, infrastructure/task/scripts/create-go-and-bnf-consumer-and-secrets.mjs, infrastructure/task/scripts/create-update-node-env-variables.mjs
This PR makes a few corrections to have we add a GO project to a site
Just read it - can be tested on canary
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-358
=> Corrections to getting go live

infrastructure/environments/dplplat01/sites.yaml
Add GO to BNF project
Just read it 
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-358
=> add go to staging

infrastructure/environments/dplplat01/sites.yaml
Well, it makes sure that albertslund is using latest go pilot setup - surprise 🎉
=> Make sure that albertslund is using latest go pilot setup

infrastructure/task/scripts/create-go-and-bnf-consumer-and-secrets.mjs, infrastructure/task/scripts/create-update-node-env-variables.mjs
We want to clean up the environment variables, so we don't have duplicates and  only use them on the project level, when that is what makes sense 
This can't easily be tested.
Just read it 
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-366
=> Set env variables on project level

infrastructure/environments/dplplat01/sites.yaml
This is the release for week 23, which looks like this: 
Redaktører:
Prod: 2025.23.0
Webmasters:
Prod: 2025.21.2
Moduletest: 2025.23.0
GO piloterne
Prod: 2025.23.0
Moduletest: 2025.23.0
GO: 0.25.13
Just read it 
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-368
=> Release week 23

infrastructure/environments/dplplat01/sites.yaml
Main change: fix unilogin login
=> New Go-only release

infrastructure/environments/dplplat01/sites.yaml
=> Deploy release 2025.24.1 to staging

infrastructure/environments/dplplat01/sites.yaml
This release according to the [plan](https://reload.zulipchat.com/#narrow/channel/419623-DDF.2B/topic/Release.202025.2E24.2E0/near/523689125)[#DDF+ > Release 2025.24.0 @ 💬](https://reload.zulipchat.com/#narrow/channel/419623-DDF.2B/topic/Release.202025.2E24.2E0/near/523689125)
Just read it 
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-370
=> Release 2025.24.1

infrastructure/environments/dplplat01/sites.yaml
=> Deploy release 2025.25.0 to staging

infrastructure/environments/dplplat01/sites.yaml
Herning is also a GO pilot now - this has been run
=> add Herning to GO pilots list

.gitignore
It ignores .env file
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-375
=> ignore .env file

infrastructure/environments/dplplat01/sites.yaml
This PR releases according to this plan:
Redaktører:
Prod: 2025.25.0
Webmasters:
Prod: 2025.24.1
Moduletest: 2025.25.0
GO Piloter
Prod: 2025.25.0
Moduletest: 2025.25.0
GO: 0.25.44
just read it 
just read it 
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-379
=> Release 2025.25.0

infrastructure/environments/dplplat01/sites.yaml
This PR amends the release PR by [adding 5 new libraries to the GO pilot list]([#DDF - Drift+ > Release uge 25 @ 💬](https://reload.zulipchat.com/#narrow/channel/435665-DDF---Drift.2B/topic/Release.20uge.2025/near/524844390))
Just read it 
Just read it
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-379
=> add new GO pilots

infrastructure/environments/dplplat01/sites.yaml
This removes the two unused anchors we had left in `sites.yaml`
Read it
=> remove unused anchors

infrastructure/environments/dplplat01/sites.yaml
Testing www cookie fix at Skanderborg
https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/2541/commits/c183176dfd0a3b1810bc23ab78f9f88dd2700c4e
=> Testing www cookie fix at Skanderborg

infrastructure/environments/dplplat01/sites.yaml
Releasing ver. 2025.26.0 to staging
=> Releasing ver. 2025.26.0 to staging

infrastructure/environments/dplplat01/sites.yaml
This add the next batch of GO libraries, which can be found [here](https://detdigitalefolkebibliotek.sharepoint.com/:x:/s/BibliotekernesNationaleRedaktion/EZa9ngM_XzRPrkvabksxVU0BHNvYHeT7qNtg31QPUqZXxg?e=X0JxKM)
Under the tab 25. juni batch 1
=> add the next batch of GO libraries

gitops/dplplat01/mariadb-10-6-22-production-1/templates/mariadb-server.template.yaml, gitops/dplplat01/mariadb-10-6-22-production-1/templates/sealed-mariadb-root-password-secret.yaml
This add's a sealed secret for the mariadb production server
=> add sealed secret to production mariadb server

gitops/dplplat01/argo-cd-resources/templates/projects/sites.yaml, gitops/dplplat01/argo-cd-resources/values.yaml
This adds a `sites` project in Argo
=> add sites project

gitops/dplplat01/argo-cd-resources/values.yaml, gitops/dplplat01/sites/kolding-main/Chart.yaml, gitops/dplplat01/sites/kolding-main/templates/database-grant.yaml, gitops/dplplat01/sites/kolding-main/templates/database-user.yaml, gitops/dplplat01/sites/kolding-main/templates/database.yaml, gitops/dplplat01/sites/kolding-main/templates/sealed-database-secret.yaml
add Kolding's database to Argo
=> add koldings database to Argo

gitops/dplplat01/argo-cd-resources/values.yaml, gitops/dplplat01/sites/billund-main/Chart.yaml, gitops/dplplat01/sites/billund-main/templates/database-grant.yaml, gitops/dplplat01/sites/billund-main/templates/database-user.yaml, gitops/dplplat01/sites/billund-main/templates/database.yaml, gitops/dplplat01/sites/billund-main/templates/sealed-database-secret.yaml
=> add billund database to argo

gitops/dplplat01/argo-cd-resources/values.yaml, gitops/dplplat01/sites/solrod2-main/Chart.yaml, gitops/dplplat01/sites/solrod2-main/templates/database-grant.yaml, gitops/dplplat01/sites/solrod2-main/templates/database-user.yaml, gitops/dplplat01/sites/solrod2-main/templates/database.yaml, gitops/dplplat01/sites/solrod2-main/templates/sealed-database-secret.yaml
=> add solrod database to argo

gitops/dplplat01/argo-cd-resources/values.yaml, gitops/dplplat01/sites/hvidovre-main/Chart.yaml, gitops/dplplat01/sites/hvidovre-main/templates/database-grant.yaml, gitops/dplplat01/sites/hvidovre-main/templates/database-user.yaml, gitops/dplplat01/sites/hvidovre-main/templates/database.yaml, gitops/dplplat01/sites/hvidovre-main/templates/sealed-database-secret.yaml
=> add hvidovre database to argo

gitops/dplplat01/argo-cd-resources/values.yaml, gitops/dplplat01/sites/allerod-main/Chart.yaml, gitops/dplplat01/sites/allerod-main/templates/database-grant.yaml, gitops/dplplat01/sites/allerod-main/templates/database-user.yaml, gitops/dplplat01/sites/allerod-main/templates/database.yaml, gitops/dplplat01/sites/allerod-main/templates/sealed-database-secret.yaml
=> add allrod database to argo

gitops/dplplat01/argo-cd-resources/values.yaml, gitops/dplplat01/sites/ishoj-main/Chart.yaml, gitops/dplplat01/sites/ishoj-main/templates/database-grant.yaml, gitops/dplplat01/sites/ishoj-main/templates/database-user.yaml, gitops/dplplat01/sites/ishoj-main/templates/database.yaml, gitops/dplplat01/sites/ishoj-main/templates/sealed-database-secret.yaml
=> add ishoj database to argo

gitops/dplplat01/argo-cd-resources/values.yaml, gitops/dplplat01/sites/faxe-main/Chart.yaml, gitops/dplplat01/sites/faxe-main/templates/database-grant.yaml, gitops/dplplat01/sites/faxe-main/templates/database-user.yaml, gitops/dplplat01/sites/faxe-main/templates/database.yaml, gitops/dplplat01/sites/faxe-main/templates/sealed-database-secret.yaml
add faxe-main database to argo
=> add faxe-main database to argo

gitops/dplplat01/argo-cd-resources/values.yaml, gitops/dplplat01/sites/faxe-moduletest/Chart.yaml, gitops/dplplat01/sites/faxe-moduletest/templates/database-grant.yaml, gitops/dplplat01/sites/faxe-moduletest/templates/database-user.yaml, gitops/dplplat01/sites/faxe-moduletest/templates/database.yaml, gitops/dplplat01/sites/faxe-moduletest/templates/sealed-database-secret.yaml
add faxe-moduletest database to argo
=> add faxe-moduletest database to argo

gitops/dplplat01/argo-cd-resources/values.yaml
=> make the list scanable

gitops/dplplat01/argo-cd-resources/values.yaml, gitops/dplplat01/sites/aalborg-moduletest/Chart.yaml, gitops/dplplat01/sites/aalborg-moduletest/templates/database-grant.yaml, gitops/dplplat01/sites/aalborg-moduletest/templates/database-user.yaml, gitops/dplplat01/sites/aalborg-moduletest/templates/database.yaml, gitops/dplplat01/sites/aalborg-moduletest/templates/sealed-database-secret.yaml
add aalborg-moduletest database to Argo
=> add aalborg-moduletest database to Argo

gitops/dplplat01/argo-cd-resources/values.yaml, gitops/dplplat01/sites/aalborg-main/Chart.yaml, gitops/dplplat01/sites/aalborg-main/templates/database-grant.yaml, gitops/dplplat01/sites/aalborg-main/templates/database-user.yaml, gitops/dplplat01/sites/aalborg-main/templates/database.yaml, gitops/dplplat01/sites/aalborg-main/templates/sealed-database-secret.yaml
add aalborg-main database to Argo
=> add aalborg-main database to argo

gitops/dplplat01/argo-cd-resources/values.yaml, gitops/dplplat01/sites/aabenraa-main/Chart.yaml, gitops/dplplat01/sites/aabenraa-main/templates/database-grant.yaml, gitops/dplplat01/sites/aabenraa-main/templates/database-user.yaml, gitops/dplplat01/sites/aabenraa-main/templates/database.yaml, gitops/dplplat01/sites/aabenraa-main/templates/sealed-database-secret.yaml
=> add aabenraa database to argo

gitops/dplplat01/argo-cd-resources/values.yaml, gitops/dplplat01/mariadb-test-prometheus-exporter/Chart.yaml, gitops/dplplat01/mariadb-test-prometheus-exporter/values.yaml
Test https://artifacthub.io/packages/helm/prometheus-community/prometheus-mysql-exporter on the test database
=> test mysql exporter on test database

infrastructure/environments/dplplat01/sites.yaml
Remove InLead client Jammerbugt
=> jammerbugt is an inlead customer

gitops/dplplat01/charts/mariadb/Chart.yaml
=> bump version

.github/workflows/push-mariadb-helm-chart.yaml
=> forgot to correct this

.github/workflows/push-mariadb-helm-chart.yaml
=> version => .version

gitops/dplplat01/argo-cd-resources/values.yaml, gitops/dplplat01/sites/gladsaxe-main/Chart.yaml, gitops/dplplat01/sites/gladsaxe-main/templates/sealed-database-secret.yaml
=> Add database to gladsaxe

gitops/dplplat01/argo-cd-resources/templates/projects/sites.yaml
attempt to allow sites project to get stuff from ghcr repo
=> add ghcr path to charts under repos allowed

gitops/dplplat01/argo-cd-resources/values.yaml, gitops/dplplat01/sites/glostrup-main/Chart.yaml, gitops/dplplat01/sites/glostrup-main/templates/sealed-database-secret.yaml, gitops/dplplat01/sites/greve-main/Chart.yaml, gitops/dplplat01/sites/greve-main/templates/database-secret.yaml, gitops/dplplat01/sites/greve-main/templates/sealed-database-secret.yaml, gitops/dplplat01/sites/gribskov-main/Chart.yaml, gitops/dplplat01/sites/gribskov-main/templates/sealed-database-secret.yaml, gitops/dplplat01/sites/gulborgsund-main/Chart.yaml, gitops/dplplat01/sites/gulborgsund-main/templates/sealed-database-secret.yaml, gitops/dplplat01/sites/halsnaes-main/Chart.yaml, gitops/dplplat01/sites/halsnaes-main/templates/sealed-database-secret.yaml
=> Add more databases 1

infrastructure/environments/dplplat01/sites.yaml
This PR is the release for this week.
=> release week 32

gitops/dplplat01/argo-cd-resources/values.yaml, gitops/dplplat01/mariadb-10-6-22-production-1/templates/mariadb-server.template.yaml, gitops/dplplat01/mariadb-servers/templates/mariadb-server.template.yaml, gitops/dplplat01/sites/hjorring-main/Chart.yaml, gitops/dplplat01/sites/hjorring-main/templates/sealed-database-secret.yaml, gitops/dplplat01/sites/ikast-brande-main/Chart.yaml, gitops/dplplat01/sites/ikast-brande-main/templates/sealed-database-secret.yaml, gitops/dplplat01/sites/kalundborg-main/Chart.yaml, gitops/dplplat01/sites/kalundborg-main/templates/sealed-database-secret.yaml, gitops/dplplat01/sites/kerteminde-main/Chart.yaml, gitops/dplplat01/sites/kerteminde-main/templates/sealed-database-secret.yaml, gitops/dplplat01/sites/kobenhavn-main/Chart.yaml, gitops/dplplat01/sites/kobenhavn-main/templates/sealed-database-secret.yaml, gitops/dplplat01/sites/kobenhavn-moduletest/Chart.yaml, gitops/dplplat01/sites/kobenhavn-moduletest/templates/sealed-database-secret.yaml
this adds more sites to the incluster database
=> Add more databases 5

docs/maintenance-plan.md, tools/dplsh/Dockerfile
This removes the Krew package installed in DPLSH
=> Remove krew from dplsh

docs/runbooks/fix-challenges-stuck-in-cert-manager.md
This adds a runbook on how to unstuck cert-manager
=> Add runbook on how to unstuck cert-manager

docs/runbooks/upgrading-aks.md
This PR solves the following task: https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-190
=> add line about reading changelog and breaking changes

infrastructure/environments/dplplat01/configuration/versions.env
Cert-manager has been udpated to chart version 1.17.4
=> update cert-manager another minor version

infrastructure/environments/dplplat01/sites.yaml
Deploy release 2025.34.0 to staging.
No.
Just read it.
=> Deploy release 2025.34.0 to staging

infrastructure/environments/dplplat01/sites.yaml
Deploy release 2025.36.0 to staging.
No
Just read it.
=> Deploy release 2025.36.0 to staging

infrastructure/environments/dplplat01/sites.yaml
Deploy 2025.36.1 on staging
No.
=> Deploy release 2025.36.1 to staging

infrastructure/environments/dplplat01/sites.yaml
Deploy Go 2025.36.2 on staging.
No.
=> Deploy Go 2025.36.2 on staging

infrastructure/environments/dplplat01/lagoon/lagoon-remote-values.template.yaml
This starts the Lagoon DB provider again
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-475
=> start the provider again

infrastructure/environments/dplplat01/lagoon/lagoon-remote-values.template.yaml
Heres the test for production provider
https://reload.atlassian.net/jira/software/c/projects/DDFDRIFT/boards/464?selectedIssue=DDFDRIFT-475
=> point the production provider to the tmp database to test it
